Restaurant.create(:id => 3132, :name => "12 South Tap Room", :address => "2318 12th Avenue South")
Restaurant.create(:id => 3133, :name => "1808 Main Kitchen", :address => "1808 West End Ave.")
Restaurant.create(:id => 3134, :name => "360 Bistro", :address => "6000 Hwy 100, Suite 100")
Restaurant.create(:id => 3135, :name => "4 Points By Sheraton", :address => "760 Old Hickory Blvd.")
Restaurant.create(:id => 3136, :name => "A Matter Of Taste Of Tn", :address => "2401 Franklin")
Restaurant.create(:id => 3137, :name => "Abay Ethiopian", :address => "3792 Nolensville Rd")
Restaurant.create(:id => 3138, :name => "Abay Ethiopian Restaurant", :address => "3792 Nolensville Road")
Restaurant.create(:id => 3139, :name => "Abay Ethiopian Restaurant", :address => "3792 B Nolensville Road")
Restaurant.create(:id => 3140, :name => "Abyssinia Ethiopian Rest.", :address => "991 Thompson Place")
Restaurant.create(:id => 3141, :name => "Acklen Park Cafe", :address => "3100 West End Avenue")
Restaurant.create(:id => 3142, :name => "Airport Deli", :address => "1321 Murfreesboro")
Restaurant.create(:id => 3143, :name => "Airport Deli", :address => "1321 Murfreesboro Road")
Restaurant.create(:id => 3144, :name => "Alexander’S Cafe", :address => "511 Union Street")
Restaurant.create(:id => 3145, :name => "Alexanders Cafe", :address => "511 Union Street")
Restaurant.create(:id => 3146, :name => "Alley Pub Kitchen", :address => "7040 Hwy 70 S")
Restaurant.create(:id => 3147, :name => "Allium Restaurant", :address => "501 Main St")
Restaurant.create(:id => 3148, :name => "Allium Restaurant", :address => "501 Main Street")
Restaurant.create(:id => 3149, :name => "Amerigo’S", :address => "1920 West End Avenue")
Restaurant.create(:id => 3150, :name => "Anatolia", :address => "48 White Bridge Road")
Restaurant.create(:id => 3151, :name => "Antonio’S", :address => "7097 Old Harding Road")
Restaurant.create(:id => 3152, :name => "Apple Barn Cider Barn", :address => "109 Opry Mills Drive")
Restaurant.create(:id => 3153, :name => "Applebarn", :address => "109 Opry Mills Dr.")
Restaurant.create(:id => 3154, :name => "Applebees Restaraunt", :address => "718 Thompson Lane")
Restaurant.create(:id => 3155, :name => "Applebees Restaurant", :address => "2401 Music Valley Drive")
Restaurant.create(:id => 3156, :name => "Arby’S", :address => "1809 West End Avenue")
Restaurant.create(:id => 3157, :name => "Arby’S", :address => "3146 Dickerson Road")
Restaurant.create(:id => 3158, :name => "Arby’S", :address => "3400 Lebanon Road")
Restaurant.create(:id => 3159, :name => "Arbys", :address => "1779 N Gallatin Road")
Restaurant.create(:id => 3160, :name => "Arbys", :address => "1779 N. Gallatin Pike")
Restaurant.create(:id => 3161, :name => "Arbys", :address => "1779 N. Gallatin Road")
Restaurant.create(:id => 3162, :name => "Arbys", :address => "1807 West End")
Restaurant.create(:id => 3163, :name => "Arbys", :address => "1807 West End Ave")
Restaurant.create(:id => 3164, :name => "Arbys", :address => "1807 West End Ave.")
Restaurant.create(:id => 3165, :name => "Arbys", :address => "1807 West End Avenue")
Restaurant.create(:id => 3166, :name => "Arbys", :address => "2350 Murfreesboro Road")
Restaurant.create(:id => 3167, :name => "Arbys", :address => "2750 Elm Hill Pike")
Restaurant.create(:id => 3168, :name => "Arbys", :address => "3196 Dickerson Rd")
Restaurant.create(:id => 3169, :name => "Arbys", :address => "3196 Dickerson Road")
Restaurant.create(:id => 3170, :name => "Arbys", :address => "3400 Lebanon")
Restaurant.create(:id => 3171, :name => "Arbys", :address => "3400 Lebanon Road")
Restaurant.create(:id => 3172, :name => "Arbys", :address => "4097 Nolensville Road")
Restaurant.create(:id => 3173, :name => "Arbys", :address => "855 Hillwood")
Restaurant.create(:id => 3174, :name => "Arbys", :address => "855 Hillwood Drive")
Restaurant.create(:id => 3175, :name => "Arbys", :address => "912 Conference Drive")
Restaurant.create(:id => 3176, :name => "Arbys", :address => "919 S. Gallatin Road")
Restaurant.create(:id => 3177, :name => "Arnold’S Country Kitchen", :address => "605 8th Avenue North")
Restaurant.create(:id => 3178, :name => "Arnolds Country Kitchen", :address => "605 8 Th Avenue South")
Restaurant.create(:id => 3179, :name => "Arnolds Country Kitchen", :address => "605 8th Avenue South")
Restaurant.create(:id => 3180, :name => "Asahi Japanese Restaurant", :address => "5215 Harding Road")
Restaurant.create(:id => 3181, :name => "At The Table", :address => "907 12th Avenue South")
Restaurant.create(:id => 3182, :name => "Awash Ethiopian Rest.", :address => "976 Murfreesboro Road")
Restaurant.create(:id => 3183, :name => "B & C Market Bbq", :address => "900 Rosa L. Parks Blvd")
Restaurant.create(:id => 3184, :name => "B & C Melrose Bbq", :address => "2617 Franklin Pke")
Restaurant.create(:id => 3185, :name => "B & C Melrose Bbq", :address => "2617 Franklin Road")
Restaurant.create(:id => 3186, :name => "Back To Cuba", :address => "4683 Trousdale Drive")
Restaurant.create(:id => 3187, :name => "Backyard Burger", :address => "5205 Old Hickory Blvd.")
Restaurant.create(:id => 3188, :name => "Baja Burrito", :address => "722 Thompson Lane")
Restaurant.create(:id => 3189, :name => "Baja Fresh", :address => "1720 West End")
Restaurant.create(:id => 3190, :name => "Baja Fresh Mexican Grill", :address => "2116 Greenhills Village Drive")
Restaurant.create(:id => 3191, :name => "Baja Fresh Mexican Grille", :address => "2116 Green Hills Village Drive")
Restaurant.create(:id => 3192, :name => "Baker’S Cafe", :address => "503 South Main Street")
Restaurant.create(:id => 3193, :name => "Bamboo Garden", :address => "2286 Lebanon Pike")
Restaurant.create(:id => 3194, :name => "Bar B Cutie", :address => "501 Donelson Pike")
Restaurant.create(:id => 3195, :name => "Bar B Cutie", :address => "1787 Gallaitn Road")
Restaurant.create(:id => 3196, :name => "Bar B Cutie", :address => "1787 N. Gallatin Road")
Restaurant.create(:id => 3197, :name => "Bar B Cutie", :address => "5221 Nolensville Road")
Restaurant.create(:id => 3198, :name => "Batter’D And Fried", :address => "1008 Woodland Street")
Restaurant.create(:id => 3199, :name => "Batterd And Fried", :address => "1008 Woodland Street")
Restaurant.create(:id => 3200, :name => "Bbq Of Tennessee", :address => "7158 Whites Creek")
Restaurant.create(:id => 3201, :name => "Bella Napoli", :address => "1200 Villa Place")
Restaurant.create(:id => 3202, :name => "Bellacinos", :address => "4662 Lebanon Road")
Restaurant.create(:id => 3203, :name => "Bellacinos Pizza And Grinder", :address => "4662 Lebanon Road")
Restaurant.create(:id => 3204, :name => "Bellagio Pizza & Subs", :address => "114 29th Avenue North")
Restaurant.create(:id => 3205, :name => "Bellshire Pizza", :address => "3801 Dickerson Road")
Restaurant.create(:id => 3206, :name => "Belmont College Main Kitchen", :address => "1900 Belmont Blvd")
Restaurant.create(:id => 3207, :name => "Best Mex Cafe", :address => "5252 Hickory Hollow Pkwy")
Restaurant.create(:id => 3208, :name => "Best Mex Cafe", :address => "5252 Hickory Hollow Pkwy.")
Restaurant.create(:id => 3209, :name => "Big Mama’S Kitchen", :address => "5528 Clarksville Hwy")
Restaurant.create(:id => 3210, :name => "Big Mamas Kitchen", :address => "5528 Clarksville Hwy")
Restaurant.create(:id => 3211, :name => "Bikini Beach Bar", :address => "1297 Antioch Pke")
Restaurant.create(:id => 3212, :name => "Blue Coast Burrito", :address => "465 Opry Mills Drive")
Restaurant.create(:id => 3213, :name => "Blue Coast Burrito", :address => "6900 Lenox Village")
Restaurant.create(:id => 3214, :name => "Blue Coast Burrito", :address => "6900 Lenox Village Drive")
Restaurant.create(:id => 3215, :name => "Blue Fig", :address => "6444 Nolensville Rd")
Restaurant.create(:id => 3216, :name => "Bojangles", :address => "7000 Charlotte Avenue")
Restaurant.create(:id => 3217, :name => "Bombay Garden", :address => "4858 Nolensville Road")
Restaurant.create(:id => 3218, :name => "Bones Fish & More", :address => "2597 Murfreesboro Road")
Restaurant.create(:id => 3219, :name => "Boscos", :address => "1805 21 St Avenue South")
Restaurant.create(:id => 3220, :name => "Boscos Nashville", :address => "1805 21st Avenue South")
Restaurant.create(:id => 3221, :name => "Boswells Harley Davidson Cafe", :address => "403 Fesslers Lane")
Restaurant.create(:id => 3222, :name => "Brandons Grille", :address => "217 Arcade Alley")
Restaurant.create(:id => 3223, :name => "Bread & Company", :address => "6051 Hwy 100")
Restaurant.create(:id => 3224, :name => "Bread And Company", :address => "4105 Hillsboro Road")
Restaurant.create(:id => 3225, :name => "Brewhouse 100", :address => "8098 Hwy. 100")
Restaurant.create(:id => 3226, :name => "Brewhouse West", :address => "7108 Charlotte Ave.")
Restaurant.create(:id => 3227, :name => "Bricktops Rest", :address => "3000 West End Avenue")
Restaurant.create(:id => 3228, :name => "Broadway Cafe", :address => "1100 Broadway")
Restaurant.create(:id => 3229, :name => "Brother Zs Wang Shop", :address => "1407 Dickerson Road")
Restaurant.create(:id => 3230, :name => "Brother Zs Wings", :address => "308 Douglas Avenue")
Restaurant.create(:id => 3231, :name => "Burger King", :address => "13011 Old Hickory Blvd")
Restaurant.create(:id => 3232, :name => "Burger King", :address => "13011 Old Hickory Blvd.")
Restaurant.create(:id => 3233, :name => "Burger King", :address => "14999 Old Hickory Blvd")
Restaurant.create(:id => 3234, :name => "Burger King", :address => "1501 Charlotte Avenue")
Restaurant.create(:id => 3235, :name => "Burger King", :address => "1501 Charlotte Pike")
Restaurant.create(:id => 3236, :name => "Burger King", :address => "2011 8th  Avenue South")
Restaurant.create(:id => 3237, :name => "Burger King", :address => "2011 8 Th Ave")
Restaurant.create(:id => 3238, :name => "Burger King", :address => "2011 8th Avenue South")
Restaurant.create(:id => 3239, :name => "Burger King", :address => "2104 N. Gallatin Road")
Restaurant.create(:id => 3240, :name => "Burger King", :address => "2104 North Gallatin Road")
Restaurant.create(:id => 3241, :name => "Burger King", :address => "2305 Murfreesboro Road")
Restaurant.create(:id => 3242, :name => "Burger King", :address => "2388 Lebanon Road")
Restaurant.create(:id => 3243, :name => "Burger King", :address => "2950 Nolensville")
Restaurant.create(:id => 3244, :name => "Burger King", :address => "2950 Nolensville Road")
Restaurant.create(:id => 3245, :name => "Burger King", :address => "331 N Gallatin")
Restaurant.create(:id => 3246, :name => "Burger King", :address => "331 N. Gallatin Road")
Restaurant.create(:id => 3247, :name => "Burger King", :address => "363 Harding Place")
Restaurant.create(:id => 3248, :name => "Burger King", :address => "454 Murfreesboro Road")
Restaurant.create(:id => 3249, :name => "Burger King", :address => "465 Opry Mills Drive")
Restaurant.create(:id => 3250, :name => "Burger King", :address => "5300 Hickory Hollow")
Restaurant.create(:id => 3251, :name => "Burger King", :address => "5300 Hickory Hollow Pkwy")
Restaurant.create(:id => 3252, :name => "Burger King", :address => "5320 Charlotte Pike")
Restaurant.create(:id => 3253, :name => "Burger King", :address => "7116 Hwy 70 South")
Restaurant.create(:id => 3254, :name => "Burger King", :address => "728 Gallatin Road")
Restaurant.create(:id => 3255, :name => "Burger Up", :address => "2901 12 Th Ave S")
Restaurant.create(:id => 3256, :name => "Cabana", :address => "1910 Belcourt")
Restaurant.create(:id => 3257, :name => "Cabana", :address => "1910 Belcourt Ave")
Restaurant.create(:id => 3258, :name => "Cabana", :address => "1910 Belcourt Avenue")
Restaurant.create(:id => 3259, :name => "Cabana", :address => "1910 Belmont Blvd.")
Restaurant.create(:id => 3260, :name => "Cafe Bosna", :address => "5751 Old Hickory Blvd")
Restaurant.create(:id => 3261, :name => "Cafe La Crumbs", :address => "327 Union St")
Restaurant.create(:id => 3262, :name => "Cafe La Crumbs", :address => "327 Union Street")
Restaurant.create(:id => 3263, :name => "Cafe Le Crumbs", :address => "327 Union Street")
Restaurant.create(:id => 3264, :name => "Café Le Crumbs", :address => "327 Union Street")
Restaurant.create(:id => 3265, :name => "Cafe Monnells", :address => "2826 Bransford Avenue")
Restaurant.create(:id => 3266, :name => "Cafe Nona", :address => "4427 Murphy Road")
Restaurant.create(:id => 3267, :name => "Cals Country Kitchen", :address => "222 Woodruff")
Restaurant.create(:id => 3268, :name => "Cals Country Restaurant", :address => "222 Woodruff")
Restaurant.create(:id => 3269, :name => "Calypso Cafe", :address => "301 Gallatin Road")
Restaurant.create(:id => 3270, :name => "Calypso Cafe East", :address => "301 Gallatin Road")
Restaurant.create(:id => 3271, :name => "Cantina Laredo", :address => "592 12 Th Ave S")
Restaurant.create(:id => 3272, :name => "Cantrells Bbq", :address => "829 Lischey Avenue")
Restaurant.create(:id => 3273, :name => "Captain D;S", :address => "2633 Lebanon Road")
Restaurant.create(:id => 3274, :name => "Captain D’S", :address => "3446 Lebanon Road")
Restaurant.create(:id => 3275, :name => "Captain D’S", :address => "789 Old Hickory Blvd")
Restaurant.create(:id => 3276, :name => "Captain Ds", :address => "2307 8th Avenue South")
Restaurant.create(:id => 3277, :name => "Captain Ds", :address => "2705 Murfreesboro Road")
Restaurant.create(:id => 3278, :name => "Captain Ds", :address => "3021 Dickerson Rd")
Restaurant.create(:id => 3279, :name => "Captain Ds", :address => "407 N. Gallatin")
Restaurant.create(:id => 3280, :name => "Caribbean Cafe", :address => "Hickory Hollow Mall")
Restaurant.create(:id => 3281, :name => "Caribbean Grill", :address => "5252 Hickory Hollow")
Restaurant.create(:id => 3282, :name => "Carol Ann’S Kitchen", :address => "407 Murfreesboro Road")
Restaurant.create(:id => 3283, :name => "Carolyns  Homestyle Kitchen", :address => "1305 Jefferson Street")
Restaurant.create(:id => 3284, :name => "Carolyns Homestyle Kitchen", :address => "1305 Jefferson St.")
Restaurant.create(:id => 3285, :name => "Carolyns Homestyle Kitchen", :address => "1305 Jefferson Street")
Restaurant.create(:id => 3286, :name => "Casa Fiesta Restaurant", :address => "2615 Elm Hill Pike")
Restaurant.create(:id => 3287, :name => "Castrillos Pizza", :address => "1404 Mc Gavock Pike")
Restaurant.create(:id => 3288, :name => "Cha Chahs Rest.", :address => "2013 Belmont Blvd.")
Restaurant.create(:id => 3289, :name => "Charlie Bobs Restaurant", :address => "1330 Dickerson Road")
Restaurant.create(:id => 3290, :name => "Cheeseburger Charleys", :address => "3811 Green Hills Village Drive")
Restaurant.create(:id => 3291, :name => "Cheeseburger Charleys", :address => "729 Thompson Lane")
Restaurant.create(:id => 3292, :name => "Cheeseburger Charlie’S", :address => "3811 Green Hills Village")
Restaurant.create(:id => 3293, :name => "Cheeseburger Charlies", :address => "223 4th Avenue North")
Restaurant.create(:id => 3294, :name => "Cheeseburger Charlies", :address => "4516 Harding Place")
Restaurant.create(:id => 3295, :name => "Chef Works", :address => "718 Thompson Lane")
Restaurant.create(:id => 3296, :name => "Chicago Italian Beef", :address => "5017 Nolensville Road")
Restaurant.create(:id => 3297, :name => "Chicago Style Gyro", :address => "900 Rosa L. Parks Blvd.")
Restaurant.create(:id => 3298, :name => "Chicago Style Gyros", :address => "3221 Dickerson")
Restaurant.create(:id => 3299, :name => "Chicago Style Gyros", :address => "3221 Dickerson Road")
Restaurant.create(:id => 3300, :name => "Chicago Style Gyros", :address => "346 Harding Place")
Restaurant.create(:id => 3301, :name => "Chicago Style Gyros", :address => "854 Hillwood Blvd.")
Restaurant.create(:id => 3302, :name => "Chicago Style Gyros", :address => "900 Rosa L. Parks Blvd.")
Restaurant.create(:id => 3303, :name => "Chicago Style Gyros", :address => "900 Rosa Parks Blvd")
Restaurant.create(:id => 3304, :name => "Chicago Style Gyros", :address => "901 Rivergate Pkwy.")
Restaurant.create(:id => 3305, :name => "Chick Fil A", :address => "2000 North Gallatin Pike")
Restaurant.create(:id => 3306, :name => "Chick Fil A", :address => "333 Commerce Street")
Restaurant.create(:id => 3307, :name => "Chick Fil A", :address => "2000 N. Gallatin Road")
Restaurant.create(:id => 3308, :name => "Chick Fil A", :address => "333 Commerce St")
Restaurant.create(:id => 3309, :name => "Chick Fil A", :address => "6500 Charlotte Pike")
Restaurant.create(:id => 3310, :name => "Chili Burrito", :address => "162 4th Ave. N.")
Restaurant.create(:id => 3311, :name => "Chilis", :address => "2322 West End Avenue")
Restaurant.create(:id => 3312, :name => "China King", :address => "3644 Bell Rd")
Restaurant.create(:id => 3313, :name => "China One Restaurant", :address => "2420 Lebanon Road")
Restaurant.create(:id => 3314, :name => "China Spring", :address => "3608 Anderson Road")
Restaurant.create(:id => 3315, :name => "Chinese Express", :address => "2663 Murfreesboro Road")
Restaurant.create(:id => 3316, :name => "Chipotle Mexican Grill", :address => "2825 West End Avenue")
Restaurant.create(:id => 3317, :name => "Christie Cafe", :address => "1000 Church Street")
Restaurant.create(:id => 3318, :name => "Chuck E Cheese", :address => "2070 N. Gallatin Road")
Restaurant.create(:id => 3319, :name => "Chuck E Cheese", :address => "5312 Hickory Hollow Lane")
Restaurant.create(:id => 3320, :name => "Chuck E Cheese", :address => "5312 Hickory Hollow Pkwy.")
Restaurant.create(:id => 3321, :name => "Churchs Chicken", :address => "214 S. Gallatin Road")
Restaurant.create(:id => 3322, :name => "Churchs Chicken", :address => "5644 Franklin Park Circle")
Restaurant.create(:id => 3323, :name => "Cinco De Mayo", :address => "5770 Old Hickory Blvd.")
Restaurant.create(:id => 3324, :name => "Cinco De Mayo Restaurant", :address => "358 White Bridge Road")
Restaurant.create(:id => 3325, :name => "Cinco De Mayo Restaurant", :address => "4944 Thoroughbred")
Restaurant.create(:id => 3326, :name => "City House", :address => "1222 4 Th Avenue North")
Restaurant.create(:id => 3327, :name => "City Limits", :address => "361 Clofton Drive")
Restaurant.create(:id => 3328, :name => "Copper Kettle", :address => "4004 Granny White Pike")
Restaurant.create(:id => 3329, :name => "Copper Kettle", :address => "94 Peabody Street")
Restaurant.create(:id => 3330, :name => "Coris Doghouse", :address => "106 29th Avenue North")
Restaurant.create(:id => 3331, :name => "Corkys Bar B Q", :address => "100 Franklin Road")
Restaurant.create(:id => 3332, :name => "Corner Asian Cafe", :address => "10656 Concord Rd")
Restaurant.create(:id => 3333, :name => "Corner Asian Cafe", :address => "10656 Concord Road")
Restaurant.create(:id => 3334, :name => "Corner Pub In The Woods", :address => "8058 Hwy 100")
Restaurant.create(:id => 3335, :name => "Country Cafe", :address => "605 Murfreesboro Road")
Restaurant.create(:id => 3336, :name => "Country Pride Restaurant", :address => "111 N. 1st St.")
Restaurant.create(:id => 3337, :name => "Cove Restaurant", :address => "3361 Bell Road")
Restaurant.create(:id => 3338, :name => "Cracker Barrel", :address => "235 Long Hollow Pike")
Restaurant.create(:id => 3339, :name => "Cracker Barrel", :address => "3454 Percy Priest Drive")
Restaurant.create(:id => 3340, :name => "Cracker Barrel", :address => "6941 Charlotte Pk")
Restaurant.create(:id => 3341, :name => "Crepes   3", :address => "160 4th Avenue North")
Restaurant.create(:id => 3342, :name => "Dairy King Drive In", :address => "431 Thompson Lane")
Restaurant.create(:id => 3343, :name => "Dairy Queen", :address => "1209 S. Gallatin Road")
Restaurant.create(:id => 3344, :name => "Dairy Queen", :address => "1508 Robinson Road")
Restaurant.create(:id => 3345, :name => "Dairy Queen", :address => "364 Opry Mills")
Restaurant.create(:id => 3346, :name => "Dairy Queen", :address => "7201 B Whites Creek Pike")
Restaurant.create(:id => 3347, :name => "Daltons Grill", :address => "7061 Hwy 70 South")
Restaurant.create(:id => 3348, :name => "Dan’S Café", :address => "538 Lafayette Street")
Restaurant.create(:id => 3349, :name => "Dans Cafe", :address => "538 Lafayette Street")
Restaurant.create(:id => 3350, :name => "Deborah West Catering", :address => "2200 West End Avenue")
Restaurant.create(:id => 3351, :name => "Deli & Cafe", :address => "95 White Bridge Road")
Restaurant.create(:id => 3352, :name => "Deli And Cafe", :address => "95 White Bridge Road")
Restaurant.create(:id => 3353, :name => "Deli Burrito", :address => "5324 Mt. View Road")
Restaurant.create(:id => 3354, :name => "Deli Burrito", :address => "5325 Mt. View Road")
Restaurant.create(:id => 3355, :name => "Delidaves", :address => "234 5th Avenue North")
Restaurant.create(:id => 3356, :name => "Des Surf & Turf", :address => "3825 Dickerson Rd")
Restaurant.create(:id => 3357, :name => "Dickeys", :address => "465 Opry Mills Drive")
Restaurant.create(:id => 3358, :name => "Domino’S", :address => "2109 Abbott Martin Road")
Restaurant.create(:id => 3359, :name => "Domino’S", :address => "5631 Charlotte Pike")
Restaurant.create(:id => 3360, :name => "Domino’S Pizza", :address => "1001 Thompson Lane")
Restaurant.create(:id => 3361, :name => "Domino’S Pizza", :address => "539 Paragon Mills")
Restaurant.create(:id => 3362, :name => "Domino’S Pizza", :address => "539 Paragon Mills Road")
Restaurant.create(:id => 3363, :name => "Dominos", :address => "1001 Thompson Place")
Restaurant.create(:id => 3364, :name => "Dominos", :address => "2109 Abbott Martin Road")
Restaurant.create(:id => 3365, :name => "Dominos", :address => "3041 Dickerson Road")
Restaurant.create(:id => 3366, :name => "Dominos", :address => "4224 Abbott Martin")
Restaurant.create(:id => 3367, :name => "Dominos", :address => "5631 Charlotte Pike")
Restaurant.create(:id => 3368, :name => "Dominos Pizza", :address => "1001 Thompson Lane")
Restaurant.create(:id => 3369, :name => "Dominos Pizza", :address => "1001 Thompson Place")
Restaurant.create(:id => 3370, :name => "Dominos Pizza", :address => "2109 Abbott Martin Road")
Restaurant.create(:id => 3371, :name => "Dominos Pizza", :address => "504 Donelson Pike")
Restaurant.create(:id => 3372, :name => "Dunya Kabab", :address => "2521 Nolensville Pike")
Restaurant.create(:id => 3373, :name => "Dunya Kabob", :address => "2521 B Nolensville Road")
Restaurant.create(:id => 3374, :name => "Dunya Kebab", :address => "2521   B Nolensville Road")
Restaurant.create(:id => 3375, :name => "Durango Mexican Grill", :address => "1088 Murfreesboro Road")
Restaurant.create(:id => 3376, :name => "E. Milano’S Pizza", :address => "2219 Murfreesboro Road")
Restaurant.create(:id => 3377, :name => "E. Milano’S Pizzeria", :address => "2219 Murfreesboro Road")
Restaurant.create(:id => 3378, :name => "E. Milano’S Pizzeria", :address => "6601 Sugar Valley")
Restaurant.create(:id => 3379, :name => "E. Milanos Pizzeria", :address => "6601 Sugar Valley Drive")
Restaurant.create(:id => 3380, :name => "East Eats", :address => "1172 Woodland St")
Restaurant.create(:id => 3381, :name => "Ed’S Fish & Pizza", :address => "1801 D.B. Todd Blvd")
Restaurant.create(:id => 3382, :name => "Ed’S Fish And Pizza", :address => "1801 D.B. Todd Blvd")
Restaurant.create(:id => 3383, :name => "Edgehill Cafe", :address => "6900 Lenox Village Drive")
Restaurant.create(:id => 3384, :name => "Eds Fish & Pizza", :address => "1801 D.B. Todd")
Restaurant.create(:id => 3385, :name => "Eds Fish And Pizza", :address => "1801 D.B. Todd Blvd")
Restaurant.create(:id => 3386, :name => "Einstein Bros. Bagels", :address => "719 Thompson Lane")
Restaurant.create(:id => 3387, :name => "El Chico", :address => "1132 Murfreesboro")
Restaurant.create(:id => 3388, :name => "El Chico", :address => "1132 Murfreesboro Road")
Restaurant.create(:id => 3389, :name => "El Chico Restaurant", :address => "1132 Murfreesboro Road")
Restaurant.create(:id => 3390, :name => "El Mariachi", :address => "615 Thompson Lane")
Restaurant.create(:id => 3391, :name => "El Mariachi Mexican Rest.", :address => "614 Thompson Lane")
Restaurant.create(:id => 3392, :name => "El Ranchero Mexican Rest.", :address => "63 E. Thompson Lane")
Restaurant.create(:id => 3393, :name => "El Ranchero Restaurant", :address => "63 E. Thompson")
Restaurant.create(:id => 3394, :name => "El Rey Azteca", :address => "7541 Old Hickory Blvd.")
Restaurant.create(:id => 3395, :name => "El Rey Mexican Restaurant", :address => "138 2 Nd Avenue North")
Restaurant.create(:id => 3396, :name => "Eruo Grill", :address => "1233 Antioch Pike")
Restaurant.create(:id => 3397, :name => "Euro Grill", :address => "1233 Antioch Pike")
Restaurant.create(:id => 3398, :name => "Evergreen Express", :address => "5539 Edmondson Pike")
Restaurant.create(:id => 3399, :name => "F. Scotts Restaurant", :address => "2210 Crestmoor Drive")
Restaurant.create(:id => 3400, :name => "Famous Daves", :address => "500 Old Hickory Blvd.")
Restaurant.create(:id => 3401, :name => "Famous Daves", :address => "5000 Old Hickory Blvd.")
Restaurant.create(:id => 3402, :name => "Famous Daves Bbq", :address => "5000 Old Hickory Blvd")
Restaurant.create(:id => 3403, :name => "Farmers Deli & Grill", :address => "900 Rosa Parks Blvd.")
Restaurant.create(:id => 3404, :name => "Fat Mo’S", :address => "351 White Bridge Road")
Restaurant.create(:id => 3405, :name => "Fat Mos", :address => "2509 Lebanon Road")
Restaurant.create(:id => 3406, :name => "Fat Mos", :address => "2620 Franklin Pke")
Restaurant.create(:id => 3407, :name => "Fat Mos", :address => "351 White Bridge Road")
Restaurant.create(:id => 3408, :name => "Fat Mos", :address => "6688 Nolensville Road")
Restaurant.create(:id => 3409, :name => "Fat Mos", :address => "946 Richards Road")
Restaurant.create(:id => 3410, :name => "Fattoush Cafe", :address => "1716 Charlotte Avenue")
Restaurant.create(:id => 3411, :name => "Fattoush Cafe", :address => "1716 Charlotte Pike")
Restaurant.create(:id => 3412, :name => "Fazolis", :address => "5002 Ohb")
Restaurant.create(:id => 3413, :name => "Fido", :address => "1812 21 St Avenue South")
Restaurant.create(:id => 3414, :name => "Fiesta Mexicana", :address => "416 4 Th Avenue South")
Restaurant.create(:id => 3415, :name => "Firehouse Subs", :address => "1708 Thompson Lane")
Restaurant.create(:id => 3416, :name => "Firehouse Subs", :address => "5225 Old Hickory Blvd")
Restaurant.create(:id => 3417, :name => "Firehouse Subs", :address => "5225 Old Hickory Blvd.")
Restaurant.create(:id => 3418, :name => "Firehouse Subs", :address => "6606 Charlotte")
Restaurant.create(:id => 3419, :name => "Firehouse Subs", :address => "6606 Charlotte Pike")
Restaurant.create(:id => 3420, :name => "Fish, Wangs And Thangs", :address => "2510 Murfreesboro Road")
Restaurant.create(:id => 3421, :name => "Fish, Wings & Thangs", :address => "2510 Murfreesboro Road")
Restaurant.create(:id => 3422, :name => "Fish, Wings And Thangs", :address => "2510 Murfreesboro Road")
Restaurant.create(:id => 3423, :name => "Fish, Wings And Things", :address => "249 Hermitage Avenue")
Restaurant.create(:id => 3424, :name => "Five Guys", :address => "2015 West End")
Restaurant.create(:id => 3425, :name => "Five Guys", :address => "4017 Hillsboro Road")
Restaurant.create(:id => 3426, :name => "Five Guys Burger & Fries", :address => "7026 Hwy 70 S")
Restaurant.create(:id => 3427, :name => "Five Guys Burgers & Fries", :address => "2018 West End Avenue")
Restaurant.create(:id => 3428, :name => "Five Guys Burgers And Fries", :address => "2018 West End Avenue")
Restaurant.create(:id => 3429, :name => "Five Guys Famous Burgers", :address => "2018 West End Avenue")
Restaurant.create(:id => 3430, :name => "Five Guys Famous Burgers & Fries", :address => "4017 Hillsboro Road")
Restaurant.create(:id => 3431, :name => "Fletchers", :address => "2715 Old Lebanon Road")
Restaurant.create(:id => 3432, :name => "Fletchers Pizza", :address => "2715 Old Lebanon Rd")
Restaurant.create(:id => 3433, :name => "Fox’S Pizza Den", :address => "2828 Elm Hill Pike")
Restaurant.create(:id => 3434, :name => "Foxs Pizza Den", :address => "1135 Bell Road")
Restaurant.create(:id => 3435, :name => "Foxs Pizza Den", :address => "2828 Elm Hill Pik")
Restaurant.create(:id => 3436, :name => "Foxs Pizza Den", :address => "2828 Elm Hill Pike")
Restaurant.create(:id => 3437, :name => "Foxs Pizza Den", :address => "2828 Elm Hill Pke")
Restaurant.create(:id => 3438, :name => "Frothy Monkey", :address => "2609 12th Avenue South")
Restaurant.create(:id => 3439, :name => "Fuji Yama", :address => "3736 Annex Avenue")
Restaurant.create(:id => 3440, :name => "Garden Brunch Cafe", :address => "924 Jefferson St")
Restaurant.create(:id => 3441, :name => "Geodellos Pizza", :address => "4811 I Trousdale")
Restaurant.create(:id => 3442, :name => "Ginger Thai", :address => "2861 Logan Street")
Restaurant.create(:id => 3443, :name => "Ginza Japanese Restaurant", :address => "3900 Hillsboro Road")
Restaurant.create(:id => 3444, :name => "Giovannis Kitchen", :address => "909 20th Avenue South")
Restaurant.create(:id => 3445, :name => "Giovannis Restaurant", :address => "909 20 Th Avenue South")
Restaurant.create(:id => 3446, :name => "Goodlettsville Cafe", :address => "107 A Memorial")
Restaurant.create(:id => 3447, :name => "Goodlettsville Cafe", :address => "107 A Memorial Drive")
Restaurant.create(:id => 3448, :name => "Goten Restaurant", :address => "1719 West End Avenue")
Restaurant.create(:id => 3449, :name => "Grassmere Gill & Kebab", :address => "3802 Nolensville Rd")
Restaurant.create(:id => 3450, :name => "Grassmere Grill And Kebab", :address => "3802 Nolensville Road")
Restaurant.create(:id => 3451, :name => "Grassmere Grille Kebab", :address => "3802 Nolensville Road")
Restaurant.create(:id => 3452, :name => "Great Steak", :address => "465 Opry Mills")
Restaurant.create(:id => 3453, :name => "Greek Deli", :address => "2720 Lebanon Pike")
Restaurant.create(:id => 3454, :name => "Greek Deli", :address => "2720 Lebanon Road")
Restaurant.create(:id => 3455, :name => "Greek Deli", :address => "2720 Old Lebanon Road")
Restaurant.create(:id => 3456, :name => "Gyro Avenue", :address => "1915 N. Gallatin Pike")
Restaurant.create(:id => 3457, :name => "Gyros And Kebab", :address => "1414 Charlotte Pike")
Restaurant.create(:id => 3458, :name => "Gyros And Kebabs", :address => "1414 Charlotte")
Restaurant.create(:id => 3459, :name => "Gyros Express", :address => "361 Harding Place")
Restaurant.create(:id => 3460, :name => "Gyros International", :address => "5814 Nolensville Road")
Restaurant.create(:id => 3461, :name => "Gyros Pizza", :address => "5751 Old Hickory Blvd")
Restaurant.create(:id => 3462, :name => "H & S Diner", :address => "1211 B Brick Church Pke")
Restaurant.create(:id => 3463, :name => "H & T Home Cooking", :address => "2371 Murfreesboro Road")
Restaurant.create(:id => 3464, :name => "H & T Homecooking", :address => "2371 Murfreesboro Road")
Restaurant.create(:id => 3465, :name => "Happy Belly Mobile #3", :address => "895 Murfreesboro Road")
Restaurant.create(:id => 3466, :name => "Hardee’S", :address => "110 Haywood Lane")
Restaurant.create(:id => 3467, :name => "Hardees", :address => "1000 Acron Drive")
Restaurant.create(:id => 3468, :name => "Hardees", :address => "110 Haywood Lane")
Restaurant.create(:id => 3469, :name => "Hardees", :address => "110 Haywood Ln.")
Restaurant.create(:id => 3470, :name => "Hardees", :address => "110 Haywood Lne")
Restaurant.create(:id => 3471, :name => "Hardees", :address => "1436 Robinson Road")
Restaurant.create(:id => 3472, :name => "Hardees", :address => "400 S. Cartwright")
Restaurant.create(:id => 3473, :name => "Hardees", :address => "400 South Cartwright")
Restaurant.create(:id => 3474, :name => "Hardees", :address => "4099 Nolensville Pike")
Restaurant.create(:id => 3475, :name => "Hardees", :address => "5775  Old Hickory Blvd.")
Restaurant.create(:id => 3476, :name => "Hermitage Cafe", :address => "71 Hermitage Avenue")
Restaurant.create(:id => 3477, :name => "Hermitage Steakhouse", :address => "4342 Lebanon Road")
Restaurant.create(:id => 3478, :name => "Hilton   Sports Grille", :address => "121 4th Avenue South")
Restaurant.create(:id => 3479, :name => "Hilton Suites   Main Kitchen", :address => "121 4th Avenue South")
Restaurant.create(:id => 3480, :name => "Hilton Suites Main Kitchen", :address => "121 4 Th Avenue South")
Restaurant.create(:id => 3481, :name => "Hilton Suites Main Kitchen", :address => "121 4th Avenue South")
Restaurant.create(:id => 3482, :name => "Hog Heaven", :address => "115 27th Avenue North")
Restaurant.create(:id => 3483, :name => "Hog Heaven", :address => "115 27 Th Avenue North")
Restaurant.create(:id => 3484, :name => "Holiday Inn Select", :address => "2200 Elm Hill Pike")
Restaurant.create(:id => 3485, :name => "Hotel Indigo Restaurant", :address => "1719 West End Avenue")
Restaurant.create(:id => 3486, :name => "Hotel Preston Kitchen", :address => "733 Briley Pkwy")
Restaurant.create(:id => 3487, :name => "House Of Gyros", :address => "561 Stewarts Ferry")
Restaurant.create(:id => 3488, :name => "House Of Gyros", :address => "561 Stewarts Ferry Pike")
Restaurant.create(:id => 3489, :name => "House Of Hickory", :address => "1107 Dickerson Road")
Restaurant.create(:id => 3490, :name => "House Of Kebab", :address => "210 Thompson Lane")
Restaurant.create(:id => 3491, :name => "House Of Pizza", :address => "15 Arcade")
Restaurant.create(:id => 3492, :name => "House Of Pizza", :address => "15 Arcade Alley")
Restaurant.create(:id => 3493, :name => "Hutton Hotel Main Kitchen", :address => "1808 West End Avenue")
Restaurant.create(:id => 3494, :name => "Ihop", :address => "2219 N. Gallatin Road")
Restaurant.create(:id => 3495, :name => "International Market & Restaurant", :address => "2010 Belmont Blvd.")
Restaurant.create(:id => 3496, :name => "International Market And Restaurant", :address => "2010 Belmont Blvd")
Restaurant.create(:id => 3497, :name => "Island Breeze Cafe", :address => "939 S. Gallatin Road")
Restaurant.create(:id => 3498, :name => "Istanbul", :address => "2631 Nolensville")
Restaurant.create(:id => 3499, :name => "Istanbul Restaurant", :address => "2631 Nolensville Road")
Restaurant.create(:id => 3500, :name => "J. Gumbos", :address => "#2 Arcade")
Restaurant.create(:id => 3501, :name => "Jack In The Box", :address => "1000 Capitol Funds Court")
Restaurant.create(:id => 3502, :name => "Jack In The Box", :address => "1000 Capitol Funds Drive")
Restaurant.create(:id => 3503, :name => "Jack In The Box", :address => "1084 Murfreesboro Road")
Restaurant.create(:id => 3504, :name => "Jack In The Box", :address => "1504 Hampton Street")
Restaurant.create(:id => 3505, :name => "Jack In The Box", :address => "2008 West End Ave.")
Restaurant.create(:id => 3506, :name => "Jack In The Box", :address => "2008 West End Avenue")
Restaurant.create(:id => 3507, :name => "Jack In The Box", :address => "3133 Lebanon Road")
Restaurant.create(:id => 3508, :name => "Jack In The Box", :address => "471 Old Hickory Blvd")
Restaurant.create(:id => 3509, :name => "Jack In The Box", :address => "471 Old Hickory Blvd.")
Restaurant.create(:id => 3510, :name => "Jack In The Box", :address => "471 Old Hickory Blve")
Restaurant.create(:id => 3511, :name => "Jack In The Box", :address => "5656 Old Hickory Blvd.")
Restaurant.create(:id => 3512, :name => "Jack In The Box", :address => "581 Murfreesboro Road")
Restaurant.create(:id => 3513, :name => "Jack In The Box", :address => "650 S. Gallatin Road")
Restaurant.create(:id => 3514, :name => "Jack In The Box", :address => "7655 Hwy 70 South")
Restaurant.create(:id => 3515, :name => "Jack In The Box", :address => "1000 Capitol Funds")
Restaurant.create(:id => 3516, :name => "Jamaica Way", :address => "900 Rosa L. Parks Blvd")
Restaurant.create(:id => 3517, :name => "Jc Bullseye Rest.", :address => "3248 Blackwood Drive")
Restaurant.create(:id => 3518, :name => "Jebs Sports Bar", :address => "114 28th Avenue North")
Restaurant.create(:id => 3519, :name => "Jersey Mikes", :address => "1706 N. Gallatin Rd")
Restaurant.create(:id => 3520, :name => "Jersey Mikes", :address => "1706 N. Gallatin Road")
Restaurant.create(:id => 3521, :name => "Jersey Mikes", :address => "211 Union Street")
Restaurant.create(:id => 3522, :name => "Jersey Mikes", :address => "2280 Murfreesboro Road")
Restaurant.create(:id => 3523, :name => "Jersey Mikes", :address => "5506 Old Hickory Blvd.")
Restaurant.create(:id => 3524, :name => "Jersey Mikes", :address => "5527 Edmondson Pike")
Restaurant.create(:id => 3525, :name => "Jersey Mikes", :address => "5529 Edmondson Pike")
Restaurant.create(:id => 3526, :name => "Jersey Mikes", :address => "736 Thompson Lane")
Restaurant.create(:id => 3527, :name => "Jersey Mikes Sub", :address => "1706 N. Gallatin Pike")
Restaurant.create(:id => 3528, :name => "Jersey Mikes Subs", :address => "211 Union Street")
Restaurant.create(:id => 3529, :name => "Jets Pizza", :address => "1919 N. Gallatin Road")
Restaurant.create(:id => 3530, :name => "Jets Pizza", :address => "5205 Old Hickory Blvd")
Restaurant.create(:id => 3531, :name => "Jetts Pizza", :address => "5205 Old Hickory")
Restaurant.create(:id => 3532, :name => "Jetts Pizza", :address => "5205 Old Hickory Blvd")
Restaurant.create(:id => 3533, :name => "Jim & Nicks Bbq", :address => "7004 Charlotte Pike")
Restaurant.create(:id => 3534, :name => "Jim Coneys Island", :address => "4663 Trousdale Drive")
Restaurant.create(:id => 3535, :name => "Jimmy Johns", :address => "2318 West End Avenue")
Restaurant.create(:id => 3536, :name => "Jimmy Kellys Restaurant", :address => "217 Louise Avenue")
Restaurant.create(:id => 3537, :name => "Jims Coney Island", :address => "4663 Trousdale Drive")
Restaurant.create(:id => 3538, :name => "Jims Original Coney Island", :address => "4663 Trousdale Drive")
Restaurant.create(:id => 3539, :name => "Joes Crab Shack", :address => "123 2nd Avenue South")
Restaurant.create(:id => 3540, :name => "Jonathon’S", :address => "7653 Hwy 70 South")
Restaurant.create(:id => 3541, :name => "K & F Cafe", :address => "324 S. Gallatin Road")
Restaurant.create(:id => 3542, :name => "Kabob Erbil", :address => "3734 Nolensville Road")
Restaurant.create(:id => 3543, :name => "Kabob Gyros", :address => "718 Thompson Lne")
Restaurant.create(:id => 3544, :name => "Kalmatas", :address => "3764 Hillsboro Pike")
Restaurant.create(:id => 3545, :name => "Katie’S Meat And Three", :address => "No. 10 Arcade")
Restaurant.create(:id => 3546, :name => "Kebab Gyros", :address => "2288 Metro Cetner")
Restaurant.create(:id => 3547, :name => "Kebab Gyros", :address => "73 White Bridge Road")
Restaurant.create(:id => 3548, :name => "Kebab Gyros Greek", :address => "389 Murfreesboro Road")
Restaurant.create(:id => 3549, :name => "Kentucky Fried Chicken", :address => "336 Harding Place")
Restaurant.create(:id => 3550, :name => "Kfc", :address => "1027 Rosa Parks")
Restaurant.create(:id => 3551, :name => "Kfc", :address => "2634 Murfreesboro Road")
Restaurant.create(:id => 3552, :name => "Kfc", :address => "290 Hicks Road")
Restaurant.create(:id => 3553, :name => "Kfc", :address => "2910 Clarksville")
Restaurant.create(:id => 3554, :name => "Kfc", :address => "2910 Clarksville Hwy")
Restaurant.create(:id => 3555, :name => "Kfc", :address => "2910 Gallatin Road")
Restaurant.create(:id => 3556, :name => "Kfc", :address => "336 Harding Place")
Restaurant.create(:id => 3557, :name => "Kfc", :address => "5802 Charlotte")
Restaurant.create(:id => 3558, :name => "Knock Out Wings", :address => "1300 Jefferson Street")
Restaurant.create(:id => 3559, :name => "Kobe Asian Cuisine", :address => "1609 Murfressboro Road")
Restaurant.create(:id => 3560, :name => "Krystal", :address => "1717 Charlotte Avenue")
Restaurant.create(:id => 3561, :name => "Krystal", :address => "1717 Charlotte Pike")
Restaurant.create(:id => 3562, :name => "Krystal", :address => "2044 Metro Center Blvd.")
Restaurant.create(:id => 3563, :name => "Krystal", :address => "2527 Lebanon Road")
Restaurant.create(:id => 3564, :name => "Krystal", :address => "273 Hicks Road")
Restaurant.create(:id => 3565, :name => "Krystal", :address => "401 Cartwright Street")
Restaurant.create(:id => 3566, :name => "Krystal", :address => "807 S. Gallatin Road")
Restaurant.create(:id => 3567, :name => "Krystals", :address => "1201 Murfreesboro Road")
Restaurant.create(:id => 3568, :name => "La Authentica Michaocama", :address => "1086 Murfreesboro")
Restaurant.create(:id => 3569, :name => "La Authentica Michoacana", :address => "1086 Murfreesboro Rd.")
Restaurant.create(:id => 3570, :name => "La Authentica Michocana", :address => "1086 Murfreesboro Road")
Restaurant.create(:id => 3571, :name => "La Playa Mexican Restaurant", :address => "27 Arcade")
Restaurant.create(:id => 3572, :name => "La Plaza Fiesta Mexican Restaurant", :address => "319 Harding Place")
Restaurant.create(:id => 3573, :name => "La Plaza Fiesta Mexican Restaurant", :address => "319 C Harding Place")
Restaurant.create(:id => 3574, :name => "La Terraza Restaurant", :address => "2256 Murfreesboro Road")
Restaurant.create(:id => 3575, :name => "La Terraza Taqueria Rest.", :address => "2256 Murfreesboro Road")
Restaurant.create(:id => 3576, :name => "Larrys Rest & Lounge", :address => "2572 Murfreesboro Rd")
Restaurant.create(:id => 3577, :name => "Larrys Restaurant And Lounge", :address => "2572 Murfreesboro Road")
Restaurant.create(:id => 3578, :name => "Las Maracas #3", :address => "4520 Harding Road")
Restaurant.create(:id => 3579, :name => "Las Maracas Mexican Rest.", :address => "2704 Gallatin Pike")
Restaurant.create(:id => 3580, :name => "Las Maracas Restaurant", :address => "2704 Gallatin Road")
Restaurant.create(:id => 3581, :name => "Las Marcas", :address => "2704 Gallatin Rd")
Restaurant.create(:id => 3582, :name => "Las Marcas Mexican Restaurant", :address => "2704 Gallatin Road")
Restaurant.create(:id => 3583, :name => "Las Palmas", :address => "1400 Antioch Pike")
Restaurant.create(:id => 3584, :name => "Las Palmas", :address => "1400 Antioch Pke")
Restaurant.create(:id => 3585, :name => "Las Palmas", :address => "15560 Old Hickory Blvd")
Restaurant.create(:id => 3586, :name => "Las Palmas", :address => "15560 Old Hickory Blvd.")
Restaurant.create(:id => 3587, :name => "Las Palmas", :address => "155600 Old Hickory Blvd.")
Restaurant.create(:id => 3588, :name => "Las Palmas", :address => "2617 Franklin Road")
Restaurant.create(:id => 3589, :name => "Las Palmas", :address => "5511 Charlotte Pke")
Restaurant.create(:id => 3590, :name => "Las Palmas", :address => "6688 Nolensville Road")
Restaurant.create(:id => 3591, :name => "Las Palmas", :address => "8167 Hwy 100")
Restaurant.create(:id => 3592, :name => "Las Palmas Mexican Restaurant", :address => "15560 Old Hickory Blvd")
Restaurant.create(:id => 3593, :name => "Las Pontrancas", :address => "114 Haywood Lane")
Restaurant.create(:id => 3594, :name => "Lazzaroli Pasta", :address => "1314 5th Avenue North")
Restaurant.create(:id => 3595, :name => "Lazzaroli Pasta", :address => "1314 5 Th Avenue North")
Restaurant.create(:id => 3596, :name => "Lb Markethouse", :address => "2905 12th Ave. S.")
Restaurant.create(:id => 3597, :name => "Legacy Foods", :address => "2608 Lebanon Pke")
Restaurant.create(:id => 3598, :name => "Lennys Sub Shop", :address => "2288 Lebanon")
Restaurant.create(:id => 3599, :name => "Little Caesars", :address => "3775 Nolensville")
Restaurant.create(:id => 3600, :name => "Little Caesars", :address => "400 N Gallatin")
Restaurant.create(:id => 3601, :name => "Little Caesars", :address => "400 N. Gallatin Road")
Restaurant.create(:id => 3602, :name => "Little Caesars", :address => "7090 Charlotte Pike")
Restaurant.create(:id => 3603, :name => "Little Caesars Pizza", :address => "3973 Nolensville Road")
Restaurant.create(:id => 3604, :name => "Lizzs Grille", :address => "2209 Murfreesboro Road")
Restaurant.create(:id => 3605, :name => "Loew’S Vanderbilt Plaza Grill", :address => "2100 West End Avenue")
Restaurant.create(:id => 3606, :name => "Loews Vanderbilt Main Kitchen", :address => "2100 West End Avenue")
Restaurant.create(:id => 3607, :name => "Loews Vanderbilt Plaza/Main Kitchen", :address => "2100 West End Avenue")
Restaurant.create(:id => 3608, :name => "Logans", :address => "2400 Elliston Place")
Restaurant.create(:id => 3609, :name => "Logans Roadhouse", :address => "727 Thompson Lane")
Restaurant.create(:id => 3610, :name => "Long John Silvers", :address => "2102 N. Gallatin")
Restaurant.create(:id => 3611, :name => "Longhorn Steakhouse", :address => "774 Old Hickory Blvd.")
Restaurant.create(:id => 3612, :name => "Los Tres Amigos", :address => "2606 Lebanon Pike")
Restaurant.create(:id => 3613, :name => "Los Tres Amigos", :address => "2606 Lebanon Road")
Restaurant.create(:id => 3614, :name => "Marche Artisan Foods", :address => "1000 Main Street")
Restaurant.create(:id => 3615, :name => "Margo Cafe & Bar", :address => "1017 Woodland Street")
Restaurant.create(:id => 3616, :name => "Margo Cafe And Bar", :address => "1011 Woodland Street")
Restaurant.create(:id => 3617, :name => "Margo Café And Bar", :address => "1017 Woodland Street")
Restaurant.create(:id => 3618, :name => "Margos Cafe And Bar", :address => "1017 Woodland Street")
Restaurant.create(:id => 3619, :name => "Marriott Main Kitchen", :address => "600 Marriott Drive")
Restaurant.create(:id => 3620, :name => "Mccabe Pub", :address => "4410 Murphy")
Restaurant.create(:id => 3621, :name => "Mc Cabe Pub", :address => "4410 Murphy Road")
Restaurant.create(:id => 3622, :name => "Mc Cabes Pub", :address => "4410 Murphy Road")
Restaurant.create(:id => 3623, :name => "Mc Donald’S", :address => "1006 Gallatin Road")
Restaurant.create(:id => 3624, :name => "Mc Donald’S", :address => "1006 S. Gallatin Road")
Restaurant.create(:id => 3625, :name => "Mc Donald’S", :address => "331 Harding Place")
Restaurant.create(:id => 3626, :name => "Mc Donald’S", :address => "8050 Hwy 100")
Restaurant.create(:id => 3627, :name => "Mc Donalds", :address => "1173 Murfreesboro Road")
Restaurant.create(:id => 3628, :name => "Mcdonalds", :address => "2499 Murfreesboro Road")
Restaurant.create(:id => 3629, :name => "Mc Donalds", :address => "2499 Murfreesboro Road")
Restaurant.create(:id => 3630, :name => "Mcdonalds", :address => "304 Longhollow Pike")
Restaurant.create(:id => 3631, :name => "Mcdonalds", :address => "4041 Nolensville Road")
Restaurant.create(:id => 3632, :name => "Mc Donalds", :address => "4114 Hillsboro Road")
Restaurant.create(:id => 3633, :name => "Mc Donalds", :address => "524 Murfreesboro Road")
Restaurant.create(:id => 3634, :name => "Mcdonalds", :address => "5301 Hickory Hollow")
Restaurant.create(:id => 3635, :name => "Mc Donalds", :address => "5301 Hickory Hollow Pkwy")
Restaurant.create(:id => 3636, :name => "Mc Donalds", :address => "5301 Hickory Hollow Pkwy.")
Restaurant.create(:id => 3637, :name => "Mcdonalds", :address => "906 Rivergate")
Restaurant.create(:id => 3638, :name => "Mcdonalds", :address => "Vanderbilt Medical Center")
Restaurant.create(:id => 3639, :name => "Mcdougals Village Coop", :address => "2115 Belcourt Avenue")
Restaurant.create(:id => 3640, :name => "Mc Dougals Village Coop", :address => "2115 Belcourt Avenue")
Restaurant.create(:id => 3641, :name => "Mediterranean Cuisine", :address => "204 Commerce")
Restaurant.create(:id => 3642, :name => "Meil Rest", :address => "343 53rd Avenue North")
Restaurant.create(:id => 3643, :name => "Michaelangelos", :address => "5133 Harding Road")
Restaurant.create(:id => 3644, :name => "Middle East Rest.", :address => "1602 21st Avenue South")
Restaurant.create(:id => 3645, :name => "Midtown Cafe", :address => "102 19th Avenue South")
Restaurant.create(:id => 3646, :name => "Midtown Café", :address => "102 19th Avenue South")
Restaurant.create(:id => 3647, :name => "Miel Restaurant", :address => "343 53 Rd Avenue North")
Restaurant.create(:id => 3648, :name => "Minami Japanese Restaurant", :address => "6688 Nolensville Road")
Restaurant.create(:id => 3649, :name => "Minami Japanse Restaurant", :address => "6688 Nolenvsville Road")
Restaurant.create(:id => 3650, :name => "Minawi Japanese Rest.", :address => "6688 Nolensville Pk.")
Restaurant.create(:id => 3651, :name => "Miro District", :address => "1922 Adelicia")
Restaurant.create(:id => 3652, :name => "Moes Southwest Grill", :address => "2511 West End Avenue")
Restaurant.create(:id => 3653, :name => "Moes Southwest Grill", :address => "4326 Harding Pike")
Restaurant.create(:id => 3654, :name => "Moes Southwest Grill", :address => "4326 Harding Road")
Restaurant.create(:id => 3655, :name => "Mojo Grill", :address => "2700 Broadway")
Restaurant.create(:id => 3656, :name => "Momma Charlotte Cafe", :address => "3061 Brick Church Pike")
Restaurant.create(:id => 3657, :name => "Monique’S Home Style Cooking", :address => "600 West Trinity Lane")
Restaurant.create(:id => 3658, :name => "Monterey Mexican", :address => "2641 Murfreesboro Rd")
Restaurant.create(:id => 3659, :name => "Mr Ps Buffalo Wings", :address => "2940 Murfreesboro Road")
Restaurant.create(:id => 3660, :name => "Mr. Burger", :address => "49 Lafayette St")
Restaurant.create(:id => 3661, :name => "Mrs. Winners", :address => "3232 Clarksville Hwy")
Restaurant.create(:id => 3662, :name => "Mrs. Winners", :address => "3440 Lebanon Road")
Restaurant.create(:id => 3663, :name => "Mrs. Winners", :address => "447 Murfreesboro Road")
Restaurant.create(:id => 3664, :name => "Mrs. Winners", :address => "5644 Franklin Pike Circle")
Restaurant.create(:id => 3665, :name => "Music City Grill", :address => "2416 Music Valley Drive")
Restaurant.create(:id => 3666, :name => "My Dad’S Pizza", :address => "1601 A Buchanan Street")
Restaurant.create(:id => 3667, :name => "My Dads Pizza", :address => "1601 A Buchanan")
Restaurant.create(:id => 3668, :name => "Nashville Palace", :address => "2611 Mc Gavock Pike")
Restaurant.create(:id => 3669, :name => "Nashville’S Most Wanted Pizza", :address => "207 Woodland Street")
Restaurant.create(:id => 3670, :name => "Nero’S Grill", :address => "2122 Hillsboro Road")
Restaurant.create(:id => 3671, :name => "New York Style Gyros", :address => "2919 Dickerson Road")
Restaurant.create(:id => 3672, :name => "Nick’S Famous Bbq", :address => "2817 Clarksville Hwy")
Restaurant.create(:id => 3673, :name => "Nicks Famous Bbq", :address => "2817 Clarksville Pike")
Restaurant.create(:id => 3674, :name => "No. #1 Chinese Rest.", :address => "63 East Thompson Ln.")
Restaurant.create(:id => 3675, :name => "No. 1 Chinese Rest.", :address => "2266 Murfreesboro Road")
Restaurant.create(:id => 3676, :name => "No. 1 Chinese Restaurant", :address => "2266 Murfreesboro Road")
Restaurant.create(:id => 3677, :name => "No. 308 Kitchen", :address => "407 Gallatin Road")
Restaurant.create(:id => 3678, :name => "Nooley’S", :address => "900 Rosa Parks Blvd")
Restaurant.create(:id => 3679, :name => "Nooleys", :address => "900 Rosa Parks Drive")
Restaurant.create(:id => 3680, :name => "Nuva Burrito", :address => "1000 Main Street")
Restaurant.create(:id => 3681, :name => "Nuvo Burrito", :address => "1000 Main St")
Restaurant.create(:id => 3682, :name => "Nuvo Burrito", :address => "5209 Charlotte Avenue")
Restaurant.create(:id => 3683, :name => "Nyumba Cafe", :address => "1310 Antioch Pike")
Restaurant.create(:id => 3684, :name => "Obies Italian Gourmet", :address => "2217 Elliston Place")
Restaurant.create(:id => 3685, :name => "Off The Grill", :address => "1816 Broadway")
Restaurant.create(:id => 3686, :name => "Ole Spagetti Factory", :address => "160 2nd Ave. N.")
Restaurant.create(:id => 3687, :name => "Ole Spaghetti Factory", :address => "160 2nd Ave. North")
Restaurant.create(:id => 3688, :name => "Olive Garden", :address => "1131 Bell Rd")
Restaurant.create(:id => 3689, :name => "Olive Garden", :address => "1131 Bell Road")
Restaurant.create(:id => 3690, :name => "Opryland Findleys Pub", :address => "2800 Opryland Dr")
Restaurant.create(:id => 3691, :name => "Opryland Hotel   Old Hickory Steakhouse", :address => "2800 Opryland Drive")
Restaurant.create(:id => 3692, :name => "Opryland Old Hickory Restaurant", :address => "2800 Opryland Drive")
Restaurant.create(:id => 3693, :name => "Opryland Old Hickory Steakhouse", :address => "2800 Opryland Dr")
Restaurant.create(:id => 3694, :name => "Opryland Paisanos Pizzerias", :address => "2800 Opryland Dr")
Restaurant.create(:id => 3695, :name => "Opryland Paisonas", :address => "2800 Opryland")
Restaurant.create(:id => 3696, :name => "Opryland Ristorante Volare", :address => "2800 Opryland Drive")
Restaurant.create(:id => 3697, :name => "Oriental Lunch", :address => "#3 Arcade")
Restaurant.create(:id => 3698, :name => "Osake Japanese Restaurant", :address => "2204 Elliston Place")
Restaurant.create(:id => 3699, :name => "P.M. Restaurant", :address => "2017 Belmont Blvd.")
Restaurant.create(:id => 3700, :name => "Pa Sgettis", :address => "7609 Hwy 70 S")
Restaurant.create(:id => 3701, :name => "Pa Sgettis", :address => "7609 Hwy. 70 South")
Restaurant.create(:id => 3702, :name => "Palermo Pizza", :address => "3920 Apache Trail")
Restaurant.create(:id => 3703, :name => "Palm Restaurant", :address => "140 5th Ave. South")
Restaurant.create(:id => 3704, :name => "Pancake Pantry", :address => "1796 21st Avenue South")
Restaurant.create(:id => 3705, :name => "Panda Express", :address => "2534 Powell Avenue")
Restaurant.create(:id => 3706, :name => "Panera Bread", :address => "1799 Gallatin")
Restaurant.create(:id => 3707, :name => "Panera Bread", :address => "2534 Powell Avenue")
Restaurant.create(:id => 3708, :name => "Panera Bread", :address => "401 Commerce Street")
Restaurant.create(:id => 3709, :name => "Panera Bread", :address => "406 21st Avenue South")
Restaurant.create(:id => 3710, :name => "Panera Bread", :address => "782 Ohb")
Restaurant.create(:id => 3711, :name => "Panera Bread", :address => "782 Old Hickory Blvd.")
Restaurant.create(:id => 3712, :name => "Papa John’S", :address => "222 Thompson Lane")
Restaurant.create(:id => 3713, :name => "Papa John’S", :address => "251 Old Hickory Blvd")
Restaurant.create(:id => 3714, :name => "Papa John’S", :address => "251 Old Hickory Blvd.")
Restaurant.create(:id => 3715, :name => "Papa John’S", :address => "5814 Nolensville Road")
Restaurant.create(:id => 3716, :name => "Papa Johns", :address => "2255 Murfreesboro Road")
Restaurant.create(:id => 3717, :name => "Papa Johns", :address => "2255 B Murfreesboro Rd")
Restaurant.create(:id => 3718, :name => "Papa Johns", :address => "2255 B Murfreesboro Road")
Restaurant.create(:id => 3719, :name => "Papa Johns", :address => "3604 Gallatin")
Restaurant.create(:id => 3720, :name => "Papa Johns", :address => "4004 Hillsboro")
Restaurant.create(:id => 3721, :name => "Papa Johns", :address => "4442 Lebanon")
Restaurant.create(:id => 3722, :name => "Papa Johns", :address => "5814 Nolensville Rd")
Restaurant.create(:id => 3723, :name => "Papa Johns Pizza", :address => "222 Thompson Lane")
Restaurant.create(:id => 3724, :name => "Papa Johns Pizza", :address => "2255 Murfreesboro Road")
Restaurant.create(:id => 3725, :name => "Papa Johns Pizza", :address => "2316 West End Avenue")
Restaurant.create(:id => 3726, :name => "Papa Johns Pizza", :address => "4004 Hillsboro Road")
Restaurant.create(:id => 3727, :name => "Papa Johns Pizza", :address => "4442 Lebanon Road")
Restaurant.create(:id => 3728, :name => "Papa Johns Pizza", :address => "5728 Charlotte Pike")
Restaurant.create(:id => 3729, :name => "Papa Murphys", :address => "2510 Murphy Road")
Restaurant.create(:id => 3730, :name => "Papa Murphys Pizza", :address => "2510 Murfreesboro Road")
Restaurant.create(:id => 3731, :name => "Papa Murphys Pizza", :address => "8120 Hwy 100")
Restaurant.create(:id => 3732, :name => "Papa Murphys Pizza", :address => "8120 Hwy. 100")
Restaurant.create(:id => 3733, :name => "Parisas Restaurant", :address => "2426 Nolensville Road")
Restaurant.create(:id => 3734, :name => "Park Cafe", :address => "4403 Murphy Road")
Restaurant.create(:id => 3735, :name => "Pasgettis", :address => "7609 Hwy 70 South")
Restaurant.create(:id => 3736, :name => "Penn Station", :address => "5205 Old Hickory")
Restaurant.create(:id => 3737, :name => "Petro Chili And Chips", :address => "1000 Rivergate Pkwy")
Restaurant.create(:id => 3738, :name => "Petros Chili And Chips", :address => "1000 Rivergate Pkwy")
Restaurant.create(:id => 3739, :name => "Pfunky Griddle", :address => "2800 Bransford")
Restaurant.create(:id => 3740, :name => "Phillips Delicatessen", :address => "234 5th Avenue North")
Restaurant.create(:id => 3741, :name => "Picasso Pizza", :address => "4606 Lebanon Pike")
Restaurant.create(:id => 3742, :name => "Picasso Pizza", :address => "4606 Lebanon Road")
Restaurant.create(:id => 3743, :name => "Picnic Café", :address => "4320 Harding Road")
Restaurant.create(:id => 3744, :name => "Pie In The Sky", :address => "6917 Lenox Village")
Restaurant.create(:id => 3745, :name => "Pie Wagon", :address => "1302 Division St")
Restaurant.create(:id => 3746, :name => "Pizza Done Right", :address => "215 Gifford Place")
Restaurant.create(:id => 3747, :name => "Pizza Hut", :address => "1144 S. Gallatin Road")
Restaurant.create(:id => 3748, :name => "Pizza Hut", :address => "2700 Gallatin Road")
Restaurant.create(:id => 3749, :name => "Pizza Hut", :address => "2701 Murfreesboro Road")
Restaurant.create(:id => 3750, :name => "Pizza Hut", :address => "3709 Clarksville Hwy.")
Restaurant.create(:id => 3751, :name => "Pizza Hut", :address => "4719 Andrew Jackson Pkwy.")
Restaurant.create(:id => 3752, :name => "Pizza Hut", :address => "5787 Nolensville Road")
Restaurant.create(:id => 3753, :name => "Pizza Hut", :address => "718 Thompson Lane")
Restaurant.create(:id => 3754, :name => "Pizza Hut", :address => "888 Murfreesboro Road")
Restaurant.create(:id => 3755, :name => "Pizza Hut", :address => "944 Richards Road")
Restaurant.create(:id => 3756, :name => "Pizza Hut Delivery", :address => "6410 Charlotte Pike")
Restaurant.create(:id => 3757, :name => "Pizza Pelon", :address => "559 Stewarts Ferry Pike")
Restaurant.create(:id => 3758, :name => "Pizza Perfect", :address => "1602 21st Avenue South")
Restaurant.create(:id => 3759, :name => "Pizza Perfect", :address => "4002 Granny White")
Restaurant.create(:id => 3760, :name => "Pizza Tony", :address => "2275 Murfreesboro Road")
Restaurant.create(:id => 3761, :name => "Player’S Inn", :address => "7097 B Old Harding")
Restaurant.create(:id => 3762, :name => "Popeyes", :address => "914 Jefferson Street")
Restaurant.create(:id => 3763, :name => "Popeyes Chicken", :address => "1188 Murfreesboro Road")
Restaurant.create(:id => 3764, :name => "Popeyes Chicken", :address => "13011 Old Hickory Blvd.")
Restaurant.create(:id => 3765, :name => "Pranzo Jersey Italian Cafe", :address => "1600 Division Street")
Restaurant.create(:id => 3766, :name => "Pronto Pizza", :address => "3701 Nolensville Road")
Restaurant.create(:id => 3767, :name => "Provence Bread", :address => "601 Church Street")
Restaurant.create(:id => 3768, :name => "Provence Bread And Bakery", :address => "4031 Hillsboro Pike")
Restaurant.create(:id => 3769, :name => "Pyramids Cafe", :address => "5252 Hickory Hollow Mall")
Restaurant.create(:id => 3770, :name => "Pyramids Cafe", :address => "5252 Hickory Hollow Pike")
Restaurant.create(:id => 3771, :name => "Pyramids Cafe", :address => "5252 Hickory Hollow Pkwy.")
Restaurant.create(:id => 3772, :name => "Qdoba", :address => "782 Old Hickory Blvd.")
Restaurant.create(:id => 3773, :name => "Qdoba Mexican Grill", :address => "2019 West End Avenue")
Restaurant.create(:id => 3774, :name => "Quinzos", :address => "4209 Nolensville Road")
Restaurant.create(:id => 3775, :name => "Quinzos", :address => "919 Conference Drive")
Restaurant.create(:id => 3776, :name => "Quizno’S", :address => "919 Conference Drive")
Restaurant.create(:id => 3777, :name => "Quiznos", :address => "10646 Concord")
Restaurant.create(:id => 3778, :name => "Quiznos", :address => "10646 Concord Rd")
Restaurant.create(:id => 3779, :name => "Quiznos", :address => "4205 Nolensville Road")
Restaurant.create(:id => 3780, :name => "Quiznos", :address => "555 Church St")
Restaurant.create(:id => 3781, :name => "Radisson", :address => "1112 Airport Center Drive")
Restaurant.create(:id => 3782, :name => "Rae’S Gourmet Shoppe", :address => "501 Union Street")
Restaurant.create(:id => 3783, :name => "Raes Gourmet Shoppe", :address => "501 Union Street")
Restaurant.create(:id => 3784, :name => "Raffertys Restaurant", :address => "2010 N. Gallatin Road")
Restaurant.create(:id => 3785, :name => "Rainforest Cafe", :address => "353 Opry Mills Drive")
Restaurant.create(:id => 3786, :name => "Rainforest Cafe Restaurant", :address => "353 Opry Mills Drive")
Restaurant.create(:id => 3787, :name => "Ranaissance Hotel Main Kitchen", :address => "611 Commerce Street")
Restaurant.create(:id => 3788, :name => "Ranch I", :address => "465 Opry Mills Drive")
Restaurant.create(:id => 3789, :name => "Red Lobster", :address => "1814 North Gallatin Road")
Restaurant.create(:id => 3790, :name => "Red Lobster", :address => "5259 Hickory Hollow Pkwy.")
Restaurant.create(:id => 3791, :name => "Reje Grab And Go", :address => "2815 Bransford Avenue")
Restaurant.create(:id => 3792, :name => "Renaissance Hotel   Commerce St. Grill", :address => "611 Commerce Street")
Restaurant.create(:id => 3793, :name => "Renaissance Hotel Main Kitchen", :address => "611 Commerce Street")
Restaurant.create(:id => 3794, :name => "Rhynos Grille", :address => "4610 Lebanon Pike")
Restaurant.create(:id => 3795, :name => "Ribs & Chicks", :address => "1297 Antioch Pke")
Restaurant.create(:id => 3796, :name => "Richards Cafe", :address => "4420 Whites Creek")
Restaurant.create(:id => 3797, :name => "Roly Poly", :address => "1510 21st Ave. S.")
Restaurant.create(:id => 3798, :name => "Roma Pizza", :address => "15563 Old Hickory Blvd.")
Restaurant.create(:id => 3799, :name => "Roma Pizza", :address => "2418 Elliston Place")
Restaurant.create(:id => 3800, :name => "Roma Pizza", :address => "3706 Hillsboro Road")
Restaurant.create(:id => 3801, :name => "Ruby Tuesdays", :address => "2304 Murfreesboro Road")
Restaurant.create(:id => 3802, :name => "Rumba", :address => "3009 West End Avenue")
Restaurant.create(:id => 3803, :name => "Ruth Chris Steakhouse", :address => "2100 West End Avenue")
Restaurant.create(:id => 3804, :name => "Ruths Chris", :address => "2100 West End")
Restaurant.create(:id => 3805, :name => "S’Barros", :address => "7620 Hwy 70 South")
Restaurant.create(:id => 3806, :name => "Sam’S Sushi Bar", :address => "200 4th Avenue North, Suite 441")
Restaurant.create(:id => 3807, :name => "Sams Kabab Gyros", :address => "7114 Hwy. 70 S")
Restaurant.create(:id => 3808, :name => "Sams Kabob Gyro", :address => "2304 Murfreesboro")
Restaurant.create(:id => 3809, :name => "Satay Thai Grill", :address => "2412 Elliston Place")
Restaurant.create(:id => 3810, :name => "Sbarro", :address => "1000 Rivergate Pkwy")
Restaurant.create(:id => 3811, :name => "S Barro", :address => "1000 Rivergate Pkwy")
Restaurant.create(:id => 3812, :name => "Sbarro", :address => "200 Commerce Street")
Restaurant.create(:id => 3813, :name => "Sbarro", :address => "Rivergate Mall")
Restaurant.create(:id => 3814, :name => "Sbarros", :address => "1000 Rivergate Pkwy.")
Restaurant.create(:id => 3815, :name => "Seoul Garden", :address => "4928 Edmondson Pike")
Restaurant.create(:id => 3816, :name => "Seoul Garden Rest.", :address => "4928 Edmondson Pike")
Restaurant.create(:id => 3817, :name => "Shadowbrook", :address => "5397 Rawling Road")
Restaurant.create(:id => 3818, :name => "Shadowbrook", :address => "5397 Rawlings Road")
Restaurant.create(:id => 3819, :name => "Shalimar Restaurant", :address => "3711 Hillsboro Road")
Restaurant.create(:id => 3820, :name => "Shoneys", :address => "365 White Bridge Road")
Restaurant.create(:id => 3821, :name => "Shoneys", :address => "5304 Cane Ridge")
Restaurant.create(:id => 3822, :name => "Shoneys", :address => "791 Old Hickory Blvd.")
Restaurant.create(:id => 3823, :name => "Sicily Pizza", :address => "2268 Murfreesboro Road")
Restaurant.create(:id => 3824, :name => "Sicily Pizza", :address => "3610 Anderson Road")
Restaurant.create(:id => 3825, :name => "Sir Pizza", :address => "14907 Old Hickory Blvd")
Restaurant.create(:id => 3826, :name => "Sir Pizza", :address => "414 B S. Gallatin Road")
Restaurant.create(:id => 3827, :name => "Sir Pizza", :address => "7648 Hwy 70 South")
Restaurant.create(:id => 3828, :name => "Smiling Elephant", :address => "2213 8th Avenue South")
Restaurant.create(:id => 3829, :name => "Snappy Tomato", :address => "493 Old Hickory Blvd")
Restaurant.create(:id => 3830, :name => "Snappy Tomato Pizza", :address => "493 Old Hickory Blvd.")
Restaurant.create(:id => 3831, :name => "So Gong Dong Tofu House", :address => "1310  A Antioch Pke")
Restaurant.create(:id => 3832, :name => "Sonic", :address => "1331 Bell Rd")
Restaurant.create(:id => 3833, :name => "Sonic", :address => "1331 Bell Road")
Restaurant.create(:id => 3834, :name => "Sonic", :address => "1410 Robinson Road")
Restaurant.create(:id => 3835, :name => "Sonic", :address => "1416 Robinson Rd")
Restaurant.create(:id => 3836, :name => "Sonic", :address => "1701 Murfreesboro Road")
Restaurant.create(:id => 3837, :name => "Sonic", :address => "2312 Dickerson Road")
Restaurant.create(:id => 3838, :name => "Sonic", :address => "2787 Murfreesboro")
Restaurant.create(:id => 3839, :name => "Sonic", :address => "3904 Dickerson Rd")
Restaurant.create(:id => 3840, :name => "Sonic", :address => "3910 Gallatin Rd")
Restaurant.create(:id => 3841, :name => "Sonic", :address => "398 Harding Place")
Restaurant.create(:id => 3842, :name => "Sonic", :address => "617 Old Hickory Blvd")
Restaurant.create(:id => 3843, :name => "Sonic", :address => "7679 Hwy. 70 S")
Restaurant.create(:id => 3844, :name => "Sonic Drive In", :address => "1331 Bell Road")
Restaurant.create(:id => 3845, :name => "Sonic Drive In", :address => "1701 Murfreesboro Road")
Restaurant.create(:id => 3846, :name => "Sonic Drive In", :address => "1906 Charlotte Avenue")
Restaurant.create(:id => 3847, :name => "Sonic Drive In", :address => "2501 Franklin Pike")
Restaurant.create(:id => 3848, :name => "Sonic Drive In", :address => "3904 Dickerson Road")
Restaurant.create(:id => 3849, :name => "Sonic Drive In", :address => "414 Donelson Pike")
Restaurant.create(:id => 3850, :name => "Sonic Drive In", :address => "617 Old Hickory Blvd.")
Restaurant.create(:id => 3851, :name => "Southern Cafe", :address => "221 6 Th Avenue North")
Restaurant.create(:id => 3852, :name => "Southern Cafe", :address => "221 6th Avenue North")
Restaurant.create(:id => 3853, :name => "Soy & Rice", :address => "Hickory Hollow Mall")
Restaurant.create(:id => 3854, :name => "Sperrys Restaurant", :address => "5106 Harding Road")
Restaurant.create(:id => 3855, :name => "Spoken Word Cafe", :address => "1801 Jefferson St")
Restaurant.create(:id => 3856, :name => "Springwater", :address => "115 27 Th Avenue North")
Restaurant.create(:id => 3857, :name => "Spudz, Inc.", :address => "5908 Charlotte Pike")
Restaurant.create(:id => 3858, :name => "Steak & Pizza", :address => "1102 Gallatin Road")
Restaurant.create(:id => 3859, :name => "Steak N Shake", :address => "5000 Old Hickory Blvd.")
Restaurant.create(:id => 3860, :name => "Steak N Shake", :address => "719 Myatt Drive")
Restaurant.create(:id => 3861, :name => "Stones River Cafe", :address => "3055 Lebanon Road")
Restaurant.create(:id => 3862, :name => "Stones Rivers Cafe", :address => "3055 Lebanon Road")
Restaurant.create(:id => 3863, :name => "Strouds Bbq", :address => "327 N. Cartwright Street")
Restaurant.create(:id => 3864, :name => "Subway", :address => "1000 Rivergate Pkwy")
Restaurant.create(:id => 3865, :name => "Subway", :address => "113 North Creek Blvd.")
Restaurant.create(:id => 3866, :name => "Subway", :address => "1323 Bell Rd")
Restaurant.create(:id => 3867, :name => "Subway", :address => "1323 Bell Road")
Restaurant.create(:id => 3868, :name => "Subway", :address => "1414 Charlotte Avenue")
Restaurant.create(:id => 3869, :name => "Subway", :address => "1414 Charlotte Pike")
Restaurant.create(:id => 3870, :name => "Subway", :address => "1427 Robinson Rd")
Restaurant.create(:id => 3871, :name => "Subway", :address => "1427 Robinson Road")
Restaurant.create(:id => 3872, :name => "Subway", :address => "15564 Old Hickory Blvd.")
Restaurant.create(:id => 3873, :name => "Subway", :address => "162 4 Th Avenue North")
Restaurant.create(:id => 3874, :name => "Subway", :address => "162 4th Avenue North")
Restaurant.create(:id => 3875, :name => "Subway", :address => "1631 Elm Hill Pike")
Restaurant.create(:id => 3876, :name => "Subway", :address => "1703 Portland Avenue")
Restaurant.create(:id => 3877, :name => "Subway", :address => "2040 Metro Center Blvd.")
Restaurant.create(:id => 3878, :name => "Subway", :address => "2181 Nolensville")
Restaurant.create(:id => 3879, :name => "Subway", :address => "2181 Nolensville Rd")
Restaurant.create(:id => 3880, :name => "Subway", :address => "2181 Nolensville Road")
Restaurant.create(:id => 3881, :name => "Subway", :address => "222 2 Nd Ave N")
Restaurant.create(:id => 3882, :name => "Subway", :address => "2400 Patterson Street")
Restaurant.create(:id => 3883, :name => "Subway", :address => "2416 Donelson Pike")
Restaurant.create(:id => 3884, :name => "Subway", :address => "2416 Lebanon Road")
Restaurant.create(:id => 3885, :name => "Subway", :address => "2510 Murfreesboro")
Restaurant.create(:id => 3886, :name => "Subway", :address => "2510 Murfreesboro Road")
Restaurant.create(:id => 3887, :name => "Subway", :address => "2719 Jefferson St")
Restaurant.create(:id => 3888, :name => "Subway", :address => "2719 Jeffrson Street")
Restaurant.create(:id => 3889, :name => "Subway", :address => "2817 West End Avenue")
Restaurant.create(:id => 3890, :name => "Subway", :address => "300 20 Th Ave N")
Restaurant.create(:id => 3891, :name => "Subway", :address => "300 20th Avenue North")
Restaurant.create(:id => 3892, :name => "Subway", :address => "300 20th Avenue South")
Restaurant.create(:id => 3893, :name => "Subway", :address => "305 W. Trinity Lane")
Restaurant.create(:id => 3894, :name => "Subway", :address => "317  B Harding Place")
Restaurant.create(:id => 3895, :name => "Subway", :address => "317 Harding Place")
Restaurant.create(:id => 3896, :name => "Subway", :address => "317 Harding Rd")
Restaurant.create(:id => 3897, :name => "Subway", :address => "317 Harding Road")
Restaurant.create(:id => 3898, :name => "Subway", :address => "317 B Harding Place")
Restaurant.create(:id => 3899, :name => "Subway", :address => "3441 Lebanon Road")
Restaurant.create(:id => 3900, :name => "Subway", :address => "353 Murfreesboro Road")
Restaurant.create(:id => 3901, :name => "Subway", :address => "3534 Murfreesboro Road")
Restaurant.create(:id => 3902, :name => "Subway", :address => "3612 Anderson Road")
Restaurant.create(:id => 3903, :name => "Subway", :address => "3686 Bell Road")
Restaurant.create(:id => 3904, :name => "Subway", :address => "3860 Dickerson Road")
Restaurant.create(:id => 3905, :name => "Subway", :address => "3958 Clarksville Hwy")
Restaurant.create(:id => 3906, :name => "Subway", :address => "400 21st Avenue South")
Restaurant.create(:id => 3907, :name => "Subway", :address => "4040 Nolensville Road")
Restaurant.create(:id => 3908, :name => "Subway", :address => "4043 Nolensville Road")
Restaurant.create(:id => 3909, :name => "Subway", :address => "4047 Nolensville Road")
Restaurant.create(:id => 3910, :name => "Subway", :address => "4121 Hillsboro Pike")
Restaurant.create(:id => 3911, :name => "Subway", :address => "414 S. Gallatin Road")
Restaurant.create(:id => 3912, :name => "Subway", :address => "4230 Harding Road")
Restaurant.create(:id => 3913, :name => "Subway", :address => "4615 Lebanon Road")
Restaurant.create(:id => 3914, :name => "Subway", :address => "5133 Harding Road")
Restaurant.create(:id => 3915, :name => "Subway", :address => "530 Church Street")
Restaurant.create(:id => 3916, :name => "Subway", :address => "5633 Charlotte")
Restaurant.create(:id => 3917, :name => "Subway", :address => "5633 Charlotte Pike")
Restaurant.create(:id => 3918, :name => "Subway", :address => "5633 Charlotte Pke")
Restaurant.create(:id => 3919, :name => "Subway", :address => "5705 Nolensville Rd")
Restaurant.create(:id => 3920, :name => "Subway", :address => "5760 Old Hickory Blvd")
Restaurant.create(:id => 3921, :name => "Subway", :address => "5760 Old Hickory Blvd.")
Restaurant.create(:id => 3922, :name => "Subway", :address => "5765 Nolensville Road")
Restaurant.create(:id => 3923, :name => "Subway", :address => "580 Donelson Pike")
Restaurant.create(:id => 3924, :name => "Subway", :address => "601 C Old Hickory Blvd")
Restaurant.create(:id => 3925, :name => "Subway", :address => "63 E. Thompson Lane")
Restaurant.create(:id => 3926, :name => "Subway", :address => "63 East Thompson Lane")
Restaurant.create(:id => 3927, :name => "Subway", :address => "6418 Centennial")
Restaurant.create(:id => 3928, :name => "Subway", :address => "6418 Centennial Blvd")
Restaurant.create(:id => 3929, :name => "Subway", :address => "6688 Nolensville Pike")
Restaurant.create(:id => 3930, :name => "Subway", :address => "6688 Nolensville Road")
Restaurant.create(:id => 3931, :name => "Subway", :address => "7040 Charlotte Avenue")
Restaurant.create(:id => 3932, :name => "Subway", :address => "705 Main Street")
Restaurant.create(:id => 3933, :name => "Subway", :address => "7050 Charlotte Pike")
Restaurant.create(:id => 3934, :name => "Subway", :address => "718 Thompson Lane")
Restaurant.create(:id => 3935, :name => "Subway", :address => "7648 Hwy 70 South, Suite 26")
Restaurant.create(:id => 3936, :name => "Subway", :address => "7648 Hwy. 70 S")
Restaurant.create(:id => 3937, :name => "Subway", :address => "769 Bell Road")
Restaurant.create(:id => 3938, :name => "Subway", :address => "8126 Hwy 100")
Restaurant.create(:id => 3939, :name => "Subway", :address => "8126 Hwy. 100")
Restaurant.create(:id => 3940, :name => "Subway", :address => "857 Briley Parkway")
Restaurant.create(:id => 3941, :name => "Subway", :address => "857 Briley Pkwy")
Restaurant.create(:id => 3942, :name => "Subway", :address => "907 Rivergate Pkwy")
Restaurant.create(:id => 3943, :name => "Subway", :address => "907 Rivergate Pkwy.")
Restaurant.create(:id => 3944, :name => "Subway", :address => "99 White Bridge Road")
Restaurant.create(:id => 3945, :name => "Sunset Grill", :address => "2001 Belcourt")
Restaurant.create(:id => 3946, :name => "Sunset Grille", :address => "2001 Belcourt Avenue")
Restaurant.create(:id => 3947, :name => "Super Dog Hot Dog", :address => "1160 S. Gallatin Road")
Restaurant.create(:id => 3948, :name => "Super Dog Hotdog", :address => "1160 S. Gallatin Road")
Restaurant.create(:id => 3949, :name => "Sushi O Sushi", :address => "6023 Nolensville Road")
Restaurant.create(:id => 3950, :name => "Swagruha Indian Rest.", :address => "900 Rosa L. Parks Blvd.")
Restaurant.create(:id => 3951, :name => "Taco Bell", :address => "1410 Brick Church Pike")
Restaurant.create(:id => 3952, :name => "Taco Bell", :address => "2004 West End Avenue")
Restaurant.create(:id => 3953, :name => "Taco Bell", :address => "2100 N Gallatin Pike")
Restaurant.create(:id => 3954, :name => "Taco Bell", :address => "2100 N. Gallatin Road")
Restaurant.create(:id => 3955, :name => "Taco Bell", :address => "2100 North Gallatin Road")
Restaurant.create(:id => 3956, :name => "Taco Bell", :address => "2101 Metro Center")
Restaurant.create(:id => 3957, :name => "Taco Bell", :address => "2101 Metro Center Blvd")
Restaurant.create(:id => 3958, :name => "Taco Bell", :address => "2101 Metro Center Blvd.")
Restaurant.create(:id => 3959, :name => "Taco Bell", :address => "2541 Murfreesboro Road")
Restaurant.create(:id => 3960, :name => "Taco Bell", :address => "2904 Gallatin Road")
Restaurant.create(:id => 3961, :name => "Taco Bell", :address => "312 Harding Place")
Restaurant.create(:id => 3962, :name => "Taco Bell", :address => "3121 Dickerson")
Restaurant.create(:id => 3963, :name => "Taco Bell", :address => "3121 Dickerson Road")
Restaurant.create(:id => 3964, :name => "Taco Bell", :address => "4000 Nolensville Pike")
Restaurant.create(:id => 3965, :name => "Taco Bell", :address => "4000 Nolensville Road")
Restaurant.create(:id => 3966, :name => "Taco Bell", :address => "4300 Harding Road")
Restaurant.create(:id => 3967, :name => "Taco Bell", :address => "5315 Hickory Hollow")
Restaurant.create(:id => 3968, :name => "Taco Bell", :address => "5315 Hickory Hollow Lane")
Restaurant.create(:id => 3969, :name => "Taco Bell", :address => "5315 Hickory Hollow Pkwy.")
Restaurant.create(:id => 3970, :name => "Taco Bell", :address => "5510 Nolensville Pike")
Restaurant.create(:id => 3971, :name => "Taco Bell", :address => "5510 Nolensville Road")
Restaurant.create(:id => 3972, :name => "Taco Bell", :address => "6450 Charlotte")
Restaurant.create(:id => 3973, :name => "Taco Bell", :address => "6450 Charlotte Avenue")
Restaurant.create(:id => 3974, :name => "Taco Bell", :address => "6540 Charlotte Pike")
Restaurant.create(:id => 3975, :name => "Taco Bell", :address => "7659 Hwy 70 S")
Restaurant.create(:id => 3976, :name => "Taco Bell", :address => "7659 Hwy 70 South")
Restaurant.create(:id => 3977, :name => "Taco Bell", :address => "990 Murfeesboro Road")
Restaurant.create(:id => 3978, :name => "Taco Bell", :address => "990 Murfreesboro Road")
Restaurant.create(:id => 3979, :name => "Taco Bell/Pizza Hut", :address => "2101 Metro Center")
Restaurant.create(:id => 3980, :name => "Taco Bell/Pizza Hut", :address => "220 Chldrens Way")
Restaurant.create(:id => 3981, :name => "Taco Bell/Pizza Hut", :address => "2200 Children’S Way")
Restaurant.create(:id => 3982, :name => "Taco Bell/Pizza Hut", :address => "2200 Childrens Way")
Restaurant.create(:id => 3983, :name => "Taco Bell/Pizza Hut", :address => "2904 Gallatin")
Restaurant.create(:id => 3984, :name => "Taco Bell/Pizza Hut", :address => "312 Harding Place")
Restaurant.create(:id => 3985, :name => "Taco Bell/Pizza Hut", :address => "6540 Charlotte Pike")
Restaurant.create(:id => 3986, :name => "Taco Mamacito Rest.", :address => "1200 Villa Place")
Restaurant.create(:id => 3987, :name => "Tacos Y Mariscos Lopez Restaurant", :address => "890 Murfreesboro Road")
Restaurant.create(:id => 3988, :name => "Taki", :address => "5760 Old Hickory Blvd.")
Restaurant.create(:id => 3989, :name => "Tangerine Asian", :address => "831 Hamilton Crossing")
Restaurant.create(:id => 3990, :name => "Tangredi’S", :address => "2323 Elliston Place")
Restaurant.create(:id => 3991, :name => "Tangs Chinese Restaurant", :address => "5814 Nolensville Pike")
Restaurant.create(:id => 3992, :name => "Tangs Chinese Restaurant", :address => "5814 Nolensville Rd")
Restaurant.create(:id => 3993, :name => "Tangs Chinese Restaurant", :address => "5814 Nolensville Road")
Restaurant.create(:id => 3994, :name => "Taqueria Arandas", :address => "1019 S. Gallatin Road")
Restaurant.create(:id => 3995, :name => "Taqueria Arandase", :address => "1019 S. Gallatin Road")
Restaurant.create(:id => 3996, :name => "Taqueria Los Potrillos Deli", :address => "2600 Foster Avenue")
Restaurant.create(:id => 3997, :name => "Tayst Rest. & Wine Bar", :address => "2100 21st Avenue South")
Restaurant.create(:id => 3998, :name => "Tayst Restaurant And Wine Bar", :address => "2100 21 St Avenue South")
Restaurant.create(:id => 3999, :name => "Tennessee Business Enterprise/Gateway Grill", :address => "426 5th Avenue North")
Restaurant.create(:id => 4000, :name => "Tgi Fridays", :address => "1705 North Gallatin Road")
Restaurant.create(:id => 4001, :name => "Thai Star", :address => "2412 Elliston Place")
Restaurant.create(:id => 4002, :name => "Thai Taste", :address => "395 Haywood Lane")
Restaurant.create(:id => 4003, :name => "The Corner Pub", :address => "4109 4111 Hillsboro Road")
Restaurant.create(:id => 4004, :name => "The Cove Restaurant", :address => "3361 Bell Road")
Restaurant.create(:id => 4005, :name => "The Food Company", :address => "2211 Bandywood")
Restaurant.create(:id => 4006, :name => "The Greek Touch", :address => "13 Arcade")
Restaurant.create(:id => 4007, :name => "The Greek Touch", :address => "No. 13 Arcade")
Restaurant.create(:id => 4008, :name => "The Melting Pot", :address => "166 2 Nd Avenue North")
Restaurant.create(:id => 4009, :name => "The Melting Pot", :address => "166 2nd Avenue North")
Restaurant.create(:id => 4010, :name => "The Other Place", :address => "6900 Lenox Village Drive")
Restaurant.create(:id => 4011, :name => "The Pie Wagon", :address => "1302 Division Street")
Restaurant.create(:id => 4012, :name => "The Pita Pit", :address => "121 2nd Avenue North")
Restaurant.create(:id => 4013, :name => "The Rawlings", :address => "5395 Rawlings Road")
Restaurant.create(:id => 4014, :name => "The Smiling Elephant", :address => "2213 8th Ave. S.")
Restaurant.create(:id => 4015, :name => "The Tin Roof", :address => "1516 Demonbreun Street")
Restaurant.create(:id => 4016, :name => "The Veggie Cafe", :address => "1601 Riverside Drive")
Restaurant.create(:id => 4017, :name => "The Wild Hare", :address => "316 White Bridge Road")
Restaurant.create(:id => 4018, :name => "Tjs Bbq And Fish", :address => "1104 Ed Temple Blvd")
Restaurant.create(:id => 4019, :name => "Tn Business Enterprise/ Federal Courthouse", :address => "801 Broad Street")
Restaurant.create(:id => 4020, :name => "Tonys Pizza", :address => "2275 Murfreesboro Road")
Restaurant.create(:id => 4021, :name => "Toyama Japanese Rest.", :address => "15532 Old Hickory Blvd.")
Restaurant.create(:id => 4022, :name => "Ugly Mugs Coffee & Tea", :address => "1886 Eastland Avenue")
Restaurant.create(:id => 4023, :name => "Ultimate Wings", :address => "3538 W. Hamilton")
Restaurant.create(:id => 4024, :name => "University Club", :address => "2402 Garland Avenue")
Restaurant.create(:id => 4025, :name => "Uptown Cafe", :address => "2221 Murphy Road")
Restaurant.create(:id => 4026, :name => "Uptown Grill", :address => "1431 Dickerson Road")
Restaurant.create(:id => 4027, :name => "Valentinos", :address => "1907 West End Avenue")
Restaurant.create(:id => 4028, :name => "Vandy Deli", :address => "1313 21 St Ave S")
Restaurant.create(:id => 4029, :name => "Vandy Deli", :address => "1313 21st Avenue South")
Restaurant.create(:id => 4030, :name => "Varallos Too", :address => "239 4th Avenue North")
Restaurant.create(:id => 4031, :name => "Vinh Long", :address => "1061 Murfreesboro Road")
Restaurant.create(:id => 4032, :name => "Vinh Long Vietnamese", :address => "1061 Murfreesboro Road")
Restaurant.create(:id => 4033, :name => "Vinh Long Vietnamese & Japanese Rest.", :address => "1061 Murfreesboro Road")
Restaurant.create(:id => 4034, :name => "Vinh Long Vietnamese/Japanese Rest.", :address => "1061 Murfreesboro Road")
Restaurant.create(:id => 4035, :name => "Waffle House", :address => "2340 Elm Hill Pike")
Restaurant.create(:id => 4036, :name => "Waffle House", :address => "2727 Mc Gavock Pike")
Restaurant.create(:id => 4037, :name => "Waffle House", :address => "4301 Sidco Drive")
Restaurant.create(:id => 4038, :name => "Waffle House", :address => "616 Old Hickory Blvd")
Restaurant.create(:id => 4039, :name => "Waffle House", :address => "6930 Charlotte Pike")
Restaurant.create(:id => 4040, :name => "Waffle House", :address => "707 Stewarts Ferry Pike")
Restaurant.create(:id => 4041, :name => "Waffle House", :address => "790 Old Hickory Blvd.")
Restaurant.create(:id => 4042, :name => "Waffle House", :address => "816 Murfreesboro Road")
Restaurant.create(:id => 4043, :name => "Watermark Restaurant", :address => "507 12th Avenue South")
Restaurant.create(:id => 4044, :name => "Wendy’S", :address => "206 21st Avenue South")
Restaurant.create(:id => 4045, :name => "Wendy’S", :address => "36 White Bridge Road")
Restaurant.create(:id => 4046, :name => "Wendy’S", :address => "4104 Hillsboro Circle")
Restaurant.create(:id => 4047, :name => "Wendy’S", :address => "4843 Nolensville Road")
Restaurant.create(:id => 4048, :name => "Wendy’S", :address => "551 Donelson Pike")
Restaurant.create(:id => 4049, :name => "Wendy’S", :address => "5529 Edmondson Pike")
Restaurant.create(:id => 4050, :name => "Wendy’S", :address => "7120 Charlotte Pike")
Restaurant.create(:id => 4051, :name => "Wendy’S", :address => "7642 Hwy 70 South")
Restaurant.create(:id => 4052, :name => "Wendy’S", :address => "860 Elm Hill Pike")
Restaurant.create(:id => 4053, :name => "Wendys", :address => "1045 28th Avenue North")
Restaurant.create(:id => 4054, :name => "Wendys", :address => "2603 West End Avenue")
Restaurant.create(:id => 4055, :name => "Wendys", :address => "3021 Gallatin Road")
Restaurant.create(:id => 4056, :name => "Wendys", :address => "330 Harding Place")
Restaurant.create(:id => 4057, :name => "Wendys", :address => "3304 Dickerson Rd")
Restaurant.create(:id => 4058, :name => "Wendys", :address => "3419 Lebanon Road")
Restaurant.create(:id => 4059, :name => "Wendys", :address => "4104 Hillsboro Circle")
Restaurant.create(:id => 4060, :name => "Wendys", :address => "4104 Hillsboro Road")
Restaurant.create(:id => 4061, :name => "Wendys", :address => "5529 Edmondson Pike")
Restaurant.create(:id => 4062, :name => "Wendys", :address => "5640 Franklin Pike Circle")
Restaurant.create(:id => 4063, :name => "Wendys", :address => "7120 Charlotte Avenue")
Restaurant.create(:id => 4064, :name => "Wendys", :address => "7120 Charlotte Pike")
Restaurant.create(:id => 4065, :name => "Wendys", :address => "741 Thompson Lane")
Restaurant.create(:id => 4066, :name => "Wendys", :address => "7642 Hwy 70 S")
Restaurant.create(:id => 4067, :name => "Wendys", :address => "802 Vantage Way")
Restaurant.create(:id => 4068, :name => "Wendys", :address => "807 Rivergate Pkwy.")
Restaurant.create(:id => 4069, :name => "Wendys`", :address => "802 Vantage Way")
Restaurant.create(:id => 4070, :name => "Which Wich", :address => "3001 West End")
Restaurant.create(:id => 4071, :name => "White Castle", :address => "1404 Broadway")
Restaurant.create(:id => 4072, :name => "White Castle", :address => "2201 Dickerson Rd")
Restaurant.create(:id => 4073, :name => "White Castle", :address => "2201 Dickerson Road")
Restaurant.create(:id => 4074, :name => "White Castle", :address => "2901 Nolensville Pike")
Restaurant.create(:id => 4075, :name => "White Castle", :address => "2901 Nolensville Road")
Restaurant.create(:id => 4076, :name => "White Castle", :address => "5605 Charlotte Avenue")
Restaurant.create(:id => 4077, :name => "White Castle", :address => "5605 Charlotte Pike")
Restaurant.create(:id => 4078, :name => "Whitt’S Bbq", :address => "114 Old Hickory Blvd")
Restaurant.create(:id => 4079, :name => "Whitt’S Bbq", :address => "3621 Nolensville Road")
Restaurant.create(:id => 4080, :name => "Whitts", :address => "114 Old Hickory Blvd")
Restaurant.create(:id => 4081, :name => "Whitts", :address => "2535 Lebanon Road")
Restaurant.create(:id => 4082, :name => "Whitts", :address => "5211 Alabama")
Restaurant.create(:id => 4083, :name => "Whitts Bar B Q", :address => "114 Old Hickory Blvd.")
Restaurant.create(:id => 4084, :name => "Whitts Bbq", :address => "114 Old Hickory")
Restaurant.create(:id => 4085, :name => "Whitts Bbq", :address => "114 Old Hickory Blvd")
Restaurant.create(:id => 4086, :name => "Whitts Bbq", :address => "114 Old Hickory Blvd.")
Restaurant.create(:id => 4087, :name => "Whitts Bbq", :address => "1800 Antioch Pk")
Restaurant.create(:id => 4088, :name => "Whitts Bbq", :address => "2535 Lebanon Rd")
Restaurant.create(:id => 4089, :name => "Whitts Bbq", :address => "2535 Lebanon Road")
Restaurant.create(:id => 4090, :name => "Whitts Bbq", :address => "3621 Nolensville Road")
Restaurant.create(:id => 4091, :name => "Whitts Bbq", :address => "4001 Andrew Jackson Pkwy")
Restaurant.create(:id => 4092, :name => "Whitts Bbq", :address => "4601 Andrew Jackson Parkway")
Restaurant.create(:id => 4093, :name => "Whitts Bbq", :address => "4601 Andrew Jackson Pkwy.")
Restaurant.create(:id => 4094, :name => "Whitts Bbq", :address => "5211 Alabama Ave")
Restaurant.create(:id => 4095, :name => "Whitts Bbq", :address => "5211 Alabama Avenue")
Restaurant.create(:id => 4096, :name => "Whitts Bbq", :address => "5310 Harding Road")
Restaurant.create(:id => 4097, :name => "Wild Bills Beignets And Bikes", :address => "104 5 Th Ave S")
Restaurant.create(:id => 4098, :name => "Wildhorse Saloon   Main Kitchen", :address => "120 2nd Avenue North")
Restaurant.create(:id => 4099, :name => "Wildhorse Saloon Kitchen", :address => "120 2nd Ave. N.")
Restaurant.create(:id => 4100, :name => "Wildhorse Saloon Main Kitchen", :address => "120 2nd Avenue North")
Restaurant.create(:id => 4101, :name => "Wing Basket", :address => "1775 N. Gallatin")
Restaurant.create(:id => 4102, :name => "Wing Basket", :address => "1775 N. Gallatin Road")
Restaurant.create(:id => 4103, :name => "Wing Basket", :address => "5753 Nolensville Rd")
Restaurant.create(:id => 4104, :name => "Wing Basket", :address => "5753 Nolensville Road")
Restaurant.create(:id => 4105, :name => "Wing Kingz", :address => "5751 Old Hickory Blvd")
Restaurant.create(:id => 4106, :name => "Wing Stop", :address => "3921 Nolensville Rd")
Restaurant.create(:id => 4107, :name => "Wing Stop", :address => "3921 Nolensville Road")
Restaurant.create(:id => 4108, :name => "Wing Stop", :address => "847 Hamilton Crossing")
Restaurant.create(:id => 4109, :name => "Yamamoto Japanese Rest.", :address => "2695 Murfreesboro Road")
Restaurant.create(:id => 4110, :name => "Yamamoto Japanese Restaurant", :address => "2695 Murfreesboro Road")
Restaurant.create(:id => 4111, :name => "Zackies", :address => "1201 5th Avenue North")
Restaurant.create(:id => 4112, :name => "Zackies", :address => "1201 5 Th Avenue North Suite 103")
Restaurant.create(:id => 4113, :name => "Zanies Restaurant", :address => "2025 8th Avenue South")
Restaurant.create(:id => 4114, :name => "Zaxbys", :address => "915 Bell Road")
Restaurant.create(:id => 4115, :name => "Zola", :address => "3001 West End Avenue")
